// vuejs-template/template-videocall/src/views/register.vue
<template>
  <!-- Main Wrapper -->
		<div class="main-wrapper">
			<div class="container-fluid">
				<div class="row">
					<div class="col-lg-12 col-xl-8 p-0">
					
						<!-- Header -->
						<header class="header">
							<nav class="navbar navbar-expand-lg header-nav">
								<div class="navbar-header">
									<a href="javascript:void(0);" class="navbar-brand logo">
										<img src="../assets/img/logo.png" class="img-fluid" alt="Logo">
									</a>
								</div>
								
								<ul class="nav header-navbar-rht log-user">
									<li class="nav-item">
										<router-link class="nav-link" to="/">Sign In</router-link>
									</li>
									<li class="nav-item">
										<router-link class="nav-link header-login" to="/register">Sign Up</router-link>
									</li>
								</ul>
							</nav>
						</header>
						<!-- /Header -->
						
						<!-- Register -->
						<div class="login-wrapper">
							<div class="loginbox">
								<h1>Sign Up to VideoCall</h1>
								<p class="account-subtitle">Register your account</p>
											
								<form>
									<div class="row">
										<div class="col-md-6">
											<div class="form-group">
												<label class="form-control-label">First Name</label>
												<input type="text" class="form-control">
											</div>
										</div>
										<div class="col-md-6">
											<div class="form-group">
												<label class="form-control-label">Last Name</label>
												<input type="text" class="form-control">
											</div>
										</div>
										<div class="col-md-12">
											<div class="form-group">
												<label class="form-control-label">Email Address</label>
												<input type="email" class="form-control">
											</div>
										</div>
										<div class="col-md-6">
											<div class="form-group">
												<label class="form-control-label">Password</label>
												<input type="password" class="form-control">
											</div>
										</div>
										<div class="col-md-6">
											<div class="form-group">
												<label class="form-control-label">Confirm Password</label>
												<input type="password" class="form-control">
											</div>
										</div>
										<div class="form-group">
											<router-link class="forgot-link" to="/forgot-password">Forgot Password ?</router-link>
										</div>
										<router-link to="/">
										<div class="d-grid">
											<button class="btn btn-primary btn-signin" type="submit">Sign Up</button>
										</div>
										</router-link>
									</div>
									<div class="dont-have">Already have an account? <router-link to="/">Login</router-link></div>
									<div class="login-or">
										<p class="span-or">or</p>
									</div>
									
									<!-- Social Login -->
									<div class="social-login">
										<a><img src="../assets/img/google.png" class="img-fluid" alt="Logo"></a>
										<a><img src="../assets/img/fb.png" class="img-fluid" alt="Logo"></a>
									</div>
									<!-- /Social Login -->
									
								</form>
							</div>
						</div>
						<!-- /Register -->
					</div>
					
					<!-- Banner -->
					<div class="col-xl-4 login-bg">
						<div class="login-banner">
							<img src="../assets/img/banner.png" class="img-fluid" alt="Logo">
						</div>
					</div>
					<!-- /Banner -->
					
				</div>
			</div>
		</div>
		<!-- /Main Wrapper -->
</template>

<script>
export default {
	components: {
  },
    mounted() {
        
	},
}
</script>

// angular-template/template-videocall/src/app/all-modules/register/register.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.css']
})
export class RegisterComponent implements OnInit {

  password = 'password';
  show1 = false;

  confirmPassword = 'password';
  show2 = false;


  constructor(public router: Router) { }
  direction() {
    this.router.navigate(['/login']);
  }

  ngOnInit(): void {
    var app = document.getElementsByTagName("BODY")[0];
    app.classList.remove("darkmode");
    app.classList.remove("darkcall");
  }

  onClick(type: string) {
    if (type === 'password') {
      if (this.password === 'password') {
        this.password = 'text';
        this.show1 = true;
      } else {
        this.password = 'password';
        this.show1 = false;
      }
    } else {
      if (this.confirmPassword === 'password') {
        this.confirmPassword = 'text';
        this.show2 = true;
      } else {
        this.confirmPassword = 'password';
        this.show2 = false;
      }
    }

  }
}

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12 col-xl-6 p-0">
            
            <!-- Register -->
            <div class="login-wrapper">
                <div class="loginbox">
                    <div class="log-header">
                        <a href="javascript:void(0);" class="navbar-brand logo">
                            <img src="assets/img/logo.png" class="img-fluid" width="35" alt="Logo">
                            <span>Dreamschat</span>
                        </a>
                    </div>
                    <h1>Welcome to <span>Dreamschat</span> <br>Sign Up to gettings started.</h1>
                    <div class="form-signin">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <input type="email" class="form-control" placeholder="Email Address ">
                                    <span class="profile-views"><img src="assets/img/icon/mail-icon.svg" alt=""></span>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <input type="text" class="form-control" placeholder="First Name">
                                    <span class="profile-views"><img src="assets/img/icon/user-login.svg" alt=""></span>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <input type="text" class="form-control" placeholder="Last Name">
                                    <span class="profile-views"><img src="assets/img/icon/user-login.svg" alt=""></span>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <input [type]="password" class="form-control pass-input" placeholder="Password">
                                    <span class="profile-views feather-eye toggle-password" (click)="onClick('password')" *ngIf="show1"></span>
                                    <span class="profile-views feather-eye-off toggle-password" (click)="onClick('password')" *ngIf="!show1"></span>

                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <input [type]="confirmPassword" class="form-control pass-confirm" placeholder="Confirm Password">
                                    <span class="profile-views feather-eye reg-toggle-password" (click)="onClick('confirmPassword')" *ngIf="show2"></span>
                                    <span class="profile-views feather-eye-off reg-toggle-password" (click)="onClick('confirmPassword')" *ngIf="!show2"></span>

                                </div>
                            </div>
                            <div class="d-grid">
                                <button class="btn btn-primary btn-signin" type="submit" (click)="direction()">Sign Up</button>
                            </div>
                        </div>
                        <div class="dont-have">Don’t have an account? <a routerLink="/login">Login</a></div>
                        <div class="login-or">
                            <p class="span-or">or</p>
                        </div>
                        
                        <!-- Social Login -->
                        <div class="social-login">
                            <a href="javascript:void(0);"><img src="assets/img/google.png" class="img-fluid" alt="Logo"></a>
                            <a href="javascript:void(0);"><img src="assets/img/fb.png" class="img-fluid" alt="Logo"></a>
                        </div>
                        <!-- /Social Login -->
                        
                    </div>
                </div>
            </div>
            <!-- /Register -->
        </div>
        
        <!-- Banner -->
        <div class="col-xl-6 login-bg">
            <div class="login-banner"></div>
        </div>
        <!-- /Banner -->
        
    </div>
</div>
