// vuejs-template/template-rtl/src/views/admin/BlankPage.vue
<template>
	<div>
		<div class="main-wrapper">
			<layout-header></layout-header>
            <layout-navadmin></layout-navadmin>
           <!-- Page Wrapper -->
            <div class="page-wrapper">
                <div class="content container-fluid">
                
                    <!-- Page Header -->
                    <div class="page-header">
                        <div class="row">
                            <div class="col-sm-12">
                                <h3 class="page-title">Blank Page</h3>
                                <ul class="breadcrumb">
                                    <li class="breadcrumb-item"><router-link to="/admin/index">Dashboard</router-link></li>
                                    <li class="breadcrumb-item active">Blank Page</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <!-- /Page Header -->
                    
                    <div class="row">
                        <div class="col-sm-12">
                            Contents here
                        </div>          
                    </div>
                    
                </div>          
            </div>
            <!-- /Page Wrapper -->
		</diV>
	</div>
</template>

// reactjs-template/template2/src/admin/components/blankpage/index.jsx
import React, { Component } from "react";

class BlankPage extends Component {
  render() {
    return (
      <>
        <div className="page-wrapper">
          <div className="content container-fluid">
            <div className="page-header">
              <div className="row">
                <div className="col-sm-12">
                  <h3 className="page-title">Blank Page</h3>
                  <ul className="breadcrumb">
                    <li className="breadcrumb-item">
                      <a href="/template2/admin">Dashboard</a>
                    </li>
                    <li className="breadcrumb-item active">Blank Page</li>
                  </ul>
                </div>
              </div>
            </div>

            <div className="row">
              <div className="col-sm-12">Contents here</div>
            </div>
          </div>
        </div>
      </>
    );
  }
}

export default BlankPage;
