// reactjs-template/template2/src/frontend/pages/forgotpassword-email.jsx
import React,{ Component } from 'react';
import { BrowserRouter as Router, Route, Switch,HashRouter } from 'react-router-dom';
import { Button, Modal, Dropdown, DropdownItem, Tabs } from "react-bootstrap";

import LogoFull from '../assets/img/logo-full.png';

class Forgotpasswordemail extends Component {
	componentDidMount() {
		$('body').addClass('account-page');
	}
	constructor(props, context) {
        super(props, context);
        this.handleShow = this.handleShow.bind(this);
        this.handleClose = this.handleClose.bind(this);
        this.state = {
          show: null
        };
    }
    handleClose() {
        this.setState({show: id});
    }
    handleShow(id) {
        this.setState({show: id});
    }
	render() {
  		return (
  			<div className="main-wrapper">
	            <div className="content align-items-center">
	            	<div className="w-100 ">
						<div className="login-left">
							
							<div className="account-content">
								<div className="login-header">
									<a href="/template2/">
	                                    <img src={LogoFull} alt="" />
	                                </a>
								</div>
								<div className="form-col">
									<div className="login-text-details">
										<h3>Forgot Password</h3>
										<p>Confirm your email and enter the OTP to send to your Registered Email id.</p>
									</div>
									<form action="/template2/login-email">
										<div className="form-group">
											<label>Your Email</label>
											<input className="form-control form-control-lg group_formcontrol" name="email" type="email" />
										</div>
										<div className="form-group">
											<label className="custom-check d-flex flex-wrap pl-0 mt-3">
												Didnt recieve OTP ?  <a href="#" className="ml-1" onClick={() => this.handleShow('Otpsuccess')}> Resend OTP.</a>
											</label>
										</div>
										<div className="pt-3">
											<div className="text-center">
												<button className="btn newgroup_create btn-block d-block w-100" type="submit">Reset Password</button>
											</div>
										</div>
									</form>
								</div>
								<div className="back-btn-col text-center">
								<a href="/template2/forgotpassword-email"><span><i className="fas fa-caret-left"></i></span> Back</a>
							</div>
							</div>
						</div>
						<div className="login-right  otp-bg">
						</div>
					</div>
	            </div>

	            <Modal show={this.state.show == 'Otpsuccess'} onHide={this.handleClose} animation={true} size="md" centered className="shadow-lg">
                    <Modal.Body>
                        <div className="success-icon text-center">
							<i className="fas fa-check mb-3"></i>
							<p>OTP Sent to the Registered Email id</p>
						</div> 
						<div className="modal-close text-right">
							<div className="close-modal" onClick={() => this.setState({ show: false })}>
								<span>close</span>
							</div>
						</div>
                    </Modal.Body>
                </Modal>

            </div>
  		)
  	}
 }

 export {Forgotpasswordemail};

// vuejs-template/template2-rtl/src/views/ForgotpasswordEmail.vue
<template>
	<div class="account-page ml-minus">
		<!-- Main Wrapper -->
        <div class="main-wrapper">          
            <!-- Page Content -->
            <div class="content align-items-center">
                    
            <div class="w-100 ">
                    <div class="login-left">
                        
                        <!-- Login Tab Content -->
                        <div class="account-content">
                            <div class="login-header">
                                <router-link to="/index">
                                    <img src="../assets/img/logo-full.png" alt="">
                                </router-link>
                            </div>
                            <div class="form-col">
                                <div class="login-text-details">
                                    <h3>Forgot Password</h3>
                                    <p>Confirm your email and enter the OTP to send to your Registered Email id.</p>
                                </div>
                                <form>
                                    <div class="form-group">
                                        <label>Your Email</label>
                                        <input class="form-control form-control-lg group_formcontrol" name="email" type="email">
                                    </div>
                                    <div class="form-group">
                                        <label class="custom-check d-flex flex-wrap ps-0 mt-3">
                                            Didnt recieve OTP ?  <a href="javascript:void(0);" class="ms-1" data-bs-toggle="modal" data-bs-target="#otp-success"> Resend OTP.</a>
                                        </label>
                                    </div>
                                    <div class="pt-3">
                                        <div class="text-center">
                                        <router-link to="/login-email">
                                            <button class="btn newgroup_create btn-block d-block w-100" type="submit">Reset Password</button>
                                        </router-link>
                                        </div>
                                    </div>
                                </form>
                            </div>
                            <div class="back-btn-col text-center">
                                <router-link to="/index"><span><i class="fas fa-caret-left"></i></span> Back</router-link>
                            </div>
                        </div>
                        <!-- /Login Tab Content -->
                    </div>
                    <div class="login-right pwd-bg">
                    </div>
                </div>

            </div>      
            <!-- /Page Content -->
            
             <!-- OTP Success -->
                <div class="modal fade" id="otp-success">
                    <div class="modal-dialog modal-dialog-centered">
                        <div class="modal-content">
                            <div class="modal-body">
                                <div class="success-icon text-center">
                                    <i class="fas fa-check mb-3"></i>
                                    <p>OTP Sent to the Registered Email id</p>
                                </div>    
                                <div class="modal-close text-end">
                                    <div class="close-modal" data-bs-dismiss="modal">
                                        <span>close</span>
                                    </div>
                                </div>
                            </div>       
                        </div>
                    </div>
                </div>
            <!-- /OTP Success -->
            
        </div>
        <!-- /Main Wrapper -->
    </div>
</template>
