// vuejs-template/template-videocall/src/views/createpassword.vue
<template>
    <!-- Main Wrapper -->
		<div class="main-wrapper">
			<div class="container-fluid">
				<div class="row">
					<div class="col-lg-12 col-xl-8 p-0">
					
						<!-- Header -->
						<header class="header">
							<nav class="navbar navbar-expand-lg header-nav">
								<div class="navbar-header">
									<a href="javascript:void(0);" class="navbar-brand logo">
										<img src="../assets/img/logo.png" class="img-fluid" alt="Logo">
									</a>
								</div>
								<ul class="nav header-navbar-rht log-user">
									<li class="nav-item">
										<router-link class="nav-link" to="/">Sign In</router-link>
									</li>
									<li class="nav-item">
										<router-link class="nav-link header-login" to="/register">Sign Up</router-link>
									</li>
								</ul>
							</nav>
						</header>
						<!-- /Header -->
						
						<!-- Forgot Password -->
						<div class="login-wrapper">
							<div class="loginbox">
								<h1>Create New Password</h1>
								<p class="account-subtitle">Your New Password must be different from previously used passwords.</p>
											
								<form>
									<div class="form-group">
										<label class="form-control-label">New Password</label>
										<input type="password" class="form-control">
									</div>
									<div class="form-group">
										<label class="form-control-label">Confirm Password</label>
										<input type="password" class="form-control">
									</div>
									<router-link to="/">
									<div class="d-grid">
										<button class="btn btn-primary btn-signin" type="submit">Create</button>
									</div>
									</router-link>
									<div class="dont-have">Back to  <router-link to="/">Signin</router-link></div>
									<!-- /Social Login -->
								</form>
							</div>
						</div>
						<!-- /Forgot Password -->
						
					</div>
					
					<!-- Banner -->
					<div class="col-xl-4 login-bg">
						<div class="login-banner">
							<img src="../assets/img/banner.png" class="img-fluid" alt="Logo">
						</div>
					</div>
					<!-- /Banner -->
					
				</div>
			</div>
		</div>
		<!-- /Main Wrapper -->
</template>

<script>
export default {
	components: {
  },
    mounted() {
        
	},
}
</script>

// angular-template/template-videocall/src/app/all-modules/create-password/create-password.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-create-password',
  templateUrl: './create-password.component.html',
  styleUrls: ['./create-password.component.css']
})
export class CreatePasswordComponent implements OnInit {
  password= 'password';
  show1 = false;

  confirmPassword= 'password';
  show2 = false;

  constructor(public router:Router) { }
  direction(){
    this.router.navigate(['/login']);
  }
  ngOnInit(): void {
    var app = document.getElementsByTagName("BODY")[0];
    app.classList.remove("darkcall");
    app.classList.remove("darkmode");
  }

  onClick(type:string) {
    if (type === 'password') {
      if (this.password === 'password') {
        this.password = 'text';
        this.show1 = true;
      } else {
        this.password = 'password';
        this.show1 = false;
      }
    }else {
      if (this.confirmPassword === 'password') {
        this.confirmPassword = 'text';
        this.show2 = true;
      } else {
        this.confirmPassword = 'password';
        this.show2 = false;
      }
    }

  }
}

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12 col-xl-6 p-0">
            
            <!-- Forgot Password -->
            <div class="login-wrapper">
                <div class="loginbox">
                    <div class="log-header">
                        <a href="javascript:void(0);" class="navbar-brand logo">
                            <img src="assets/img/logo.png" class="img-fluid" width="40" alt="Logo">
                            <span>Dreamschat</span>
                        </a>
                    </div>
                    <h1>Create New Password</h1>		
                    <div class="form-signin">
                        <div class="form-group">
                            <input [type]="password" class="form-control pass-input" placeholder="Password">
                            <span class="profile-views feather-eye toggle-password" (click)="onClick('password')" *ngIf="show1"></span>
                            <span class="profile-views feather-eye-off toggle-password" (click)="onClick('password')" *ngIf="!show1"></span>

                        </div>
                        <div class="form-group">
                            <input [type]="confirmPassword" class="form-control pass-confirm" placeholder="Confirm Password">
                            <span class="profile-views feather-eye reg-toggle-password" (click)="onClick('confirmPassword')" *ngIf="show2"></span>
                            <span class="profile-views feather-eye-off reg-toggle-password" (click)="onClick('confirmPassword')" *ngIf="!show2"></span>
                        </div>
                        <div class="d-grid">
                            <button class="btn btn-primary btn-signin" type="submit" (click)="direction()">Create</button>
                        </div>
                        <div class="dont-have">Back to  <a routerLink="/dashboard">Signin</a></div>
                        <!-- /Social Login -->
                    </div>
                </div>
            </div>
            <!-- /Forgot Password -->
            
        </div>
        
        <!-- Banner -->
        <div class="col-xl-6 login-bg">
            <div class="login-banner"></div>
        </div>
        <!-- /Banner -->
        
    </div>
</div>
