// reactjs-template/template/src/admin/components/error/index.jsx
import React, { Component } from 'react';


class Error extends Component {
 componentWillMount(){
        document.body.classList.add('error-page');
    }

    componentWillUnmount(){
        document.body.classList.remove('error-page');
    }
    render() {
   
        return (
            <>
                  <div className="main-wrapper">
			
			<div className="error-box">
				<h1>404</h1>
				<h3 className="h2 mb-3"><i className="fa fa-warning"></i> Oops! Page not found!</h3>
				<p className="h4 font-weight-normal">The page you requested was not found.</p>
				<a href="/admin" className="btn btn-primary">Back to Home</a>
			</div>
		
        </div>
            </>
        )
    }
}

export default Error;

// vuejs-template/template2-rtl/src/views/admin/Error.vue
<template>
		<!-- Main Wrapper -->
        <div class="main-wrapper error-page">		
			<div class="error-box">
				<h1>404</h1>
				<h3 class="h2 mb-3"><i class="fa fa-warning"></i> Oops! Page not found!</h3>
				<p class="h4 font-weight-normal">The page you requested was not found.</p>
				<router-link to="/admin/index" class="btn btn-primary">Back to Home</router-link>
			</div>
        </div>
		<!-- /Main Wrapper -->
</template>
