// reactjs-template/template2/src/admin/components/login/index.jsx
import React, { Component } from 'react';

class Login extends Component{
    render(){
        return(
            <div className="main-wrapper login-body">
                <div className="login-wrapper">
                    <div className="container">
                        <div className="loginbox">
                            <div className="login-right">
                                <div className="login-right-wrap">
                                    <h1>Login</h1>
                                    <p className="account-subtitle">Access to our dashboard</p>                         
                                    <form action="/template2/admin">
                                        <div className="form-group">
                                            <input className="form-control" type="text" placeholder="Email" />
                                        </div>
                                        <div className="form-group">
                                            <input className="form-control" type="text" placeholder="Password" />
                                        </div>
                                        <div className="form-group">
                                            <button className="btn btn-primary btn-block" type="submit">Login</button>
                                        </div>
                                    </form>         
                                    <div className="text-center forgotpass"><a href="/template2/admin/forgotpassword">Forgot Password?</a></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>       
        )
     }
  }
  
 export default Login;

// vuejs-template/template2-rtl/src/views/admin/Login.vue
<template>
	<!-- Main Wrapper -->
    <div class="main-wrapper login-body">
     <div class="login-wrapper">
                <div class="container">
                    <div class="loginbox">
                        <div class="login-right">
                            <div class="login-right-wrap">
                                <h1>Login</h1>
                                <p class="account-subtitle">Access to our dashboard</p>                         
                                <!-- Form -->
                                <form>
                                    <div class="form-group">
                                        <input class="form-control" type="text" placeholder="Email">
                                    </div>
                                    <div class="form-group">
                                        <input class="form-control" type="text" placeholder="Password">
                                    </div>
                                    <div class="form-group">
                                    <router-link to="/admin/index">
                                        <button class="btn btn-primary btn-block" type="submit">Login</button>
                                    </router-link>
                                    </div>
                                </form>
                                <!-- /Form -->
                                
                                <div class="text-center forgotpass"><router-link to="/admin/forgot-password">Forgot Password?</router-link></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    </div>
    <!-- /Main Wrapper -->
</template>
