// angular-template/template-videocall/src/app/all-modules/forgot-password/forgot-password.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-forgot-password',
  templateUrl: './forgot-password.component.html',
  styleUrls: ['./forgot-password.component.css']
})
export class ForgotPasswordComponent implements OnInit {

  constructor(public router: Router) { }
  direction(){
    this.router.navigate(['/create-password']);
  }
  ngOnInit(): void {
    var app = document.getElementsByTagName("BODY")[0];
    app.classList.remove("darkcall");
  }
  ngAfterViewInit() {
    this.loadjs("assets/js/script.js")
  }
  loadjs(js) {
    var script = document.createElement('script');
    script.src = js;
    script.async = false;
    document.body.appendChild(script);
  }
}

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12 col-xl-6 p-0">
            
            <!-- Forgot Password -->
            <div class="login-wrapper">
                <div class="loginbox">
                    <div class="log-header">
                        <a routerLink="/dashboard" class="navbar-brand logo">
                            <img src="assets/img/logo.png" class="img-fluid" width="40" alt="Logo">
                            <span>Dreamschat</span>
                        </a>
                    </div>
                    <h1>Forgot Password</h1>	
                    <div class="form-signin">
                        <div class="form-group">
                            <input type="email" class="form-control" placeholder="Email Address ">
                            <span class="profile-views"><img src="assets/img/icon/mail-icon.svg" alt=""></span>
                        </div>
                        <div class="d-grid">
                            <button class="btn btn-primary btn-signin" type="submit" (click)="direction()">Send</button>
                        </div>
                        <div class="dont-have">Back to <a routerLink="/dashboard">Sign In</a></div>
                        <!-- /Social Login -->
                    </div>
                </div>
            </div>
            <!-- /Forgot Password -->
            
        </div>
        
        <!-- Banner -->
        <div class="col-xl-6 login-bg">
            <div class="login-banner"></div>
        </div>
        <!-- /Banner -->
        
    </div>
</div>

// vuejs-template/template-videocall/src/views/forgotpassword.vue
<template>
 <!-- Main Wrapper -->
		<div class="main-wrapper">
			<div class="container-fluid">
				<div class="row">
					<div class="col-lg-12 col-xl-8 p-0">
					
						<!-- Header -->
						<header class="header">
							<nav class="navbar navbar-expand-lg header-nav">
								<div class="navbar-header">
									<a href="javascript:void(0);" class="navbar-brand logo">
										<img src="../assets/img/logo.png" class="img-fluid" alt="Logo">
									</a>
								</div>
								<ul class="nav header-navbar-rht log-user">
									<li class="nav-item">
										<router-link class="nav-link" to="/">Sign In</router-link>
									</li>
									<li class="nav-item">
										<router-link class="nav-link header-login" to="/register">Sign Up</router-link>
									</li>
								</ul>
							</nav>
						</header>
						<!-- /Header -->
						
						<!-- Forgot Password -->
						<div class="login-wrapper">
							<div class="loginbox">
								<h1>Forgot Password</h1>
								<p class="account-subtitle">Enter Your Registered email below to receive password reset instruction</p>
											
								<form>
									<div class="form-group">
										<label class="form-control-label">Email Address</label>
										<input type="email" class="form-control">
									</div>
									<router-link to="create-password">
									<div class="d-grid">
										<button class="btn btn-primary btn-signin" type="submit">Send</button>
									</div>
									</router-link>
									<div class="dont-have">Back to  <router-link to="/">Signin</router-link></div>
									<!-- /Social Login -->
								</form>
							</div>
						</div>
						<!-- /Forgot Password -->
						
					</div>
					
					<!-- Banner -->
					<div class="col-xl-4 login-bg">
						<div class="login-banner">
							<img src="../assets/img/banner.png" class="img-fluid" alt="Logo">
						</div>
					</div>
					<!-- /Banner -->
					
				</div>
			</div>
		</div>
		<!-- /Main Wrapper -->
</template>

<script>
export default {
	components: {
  },
    mounted() {
        
	},
}
</script>
