// angular-template/template-videocall/src/app/all-modules/join-call/join-call.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-join-call',
  templateUrl: './join-call.component.html',
  styleUrls: ['./join-call.component.css']
})
export class JoinCallComponent implements OnInit {
  public toggleValue: boolean = false;

  constructor() { }
  ngOnInit(): void {
    var app = document.getElementsByTagName("BODY")[0];
    app.classList.remove("darkcall");
  }
  ngAfterViewInit() {
    this.loadjs1("assets/js/script.js")
  }
  loadjs1(js) {
    var script = document.createElement('script');
    script.src = js;
    script.async = false;
    document.body.appendChild(script);
  }
  toggle() {
    this.toggleValue = !this.toggleValue;
    const bodyTag = document.body;
    if (this.toggleValue) {
      bodyTag.classList.add('mini-sidebar');
    }
    else {
      bodyTag.classList.remove('mini-sidebar')
    }
  }
  onMouseChange(event: string) {
    const bodyTag = document.body;
    if (this.toggleValue) {
      if (event === 'mouseover') {
        bodyTag.classList.add('mini-sidebar');
        bodyTag.classList.add('expand-menu');
      }
      else if (event === 'mouseout') {
        bodyTag.classList.remove('expand-menu');
      }
    }
  }
  toggleMobile() {
    this.toggleValue = !this.toggleValue;
    var root = document.getElementsByTagName( 'html' )[0];
    var mainWrapper = document.getElementsByClassName('main-wrapper')[0];
    var sidebar:any = document.getElementById('sidebar')

    if (this.toggleValue) {
      root.classList.add('menu-opened');
      mainWrapper.classList.add('slide-nav');
      sidebar.classList.add('opened');
    }
    else {
      root.classList.remove('menu-opened');
      mainWrapper.classList.remove('slide-nav');
      sidebar.classList.remove('opened');
    }
  }
}

<div class="header header-two">
    <div class="header-left">
        <a routerLink="/dashboard" class="logo-one">
            <img src="assets/img/logo.png" width="35" height="35" alt="">
        </a>
    </div>
    <a id="chat_toggle_btn" (click)="toggle()"><img src="assets/img/icon/bar-icon.svg"  alt=""></a>
    <a id="mobile_btn_chat" class="mobile_btn_chat float-start" (click)="toggleMobile()"><img src="assets/img/icon/bar-icon.svg"  alt=""></a>
    <div class="chat-menus chat-top-menu">
        <ul class="nav">
            <li>
                <a routerLink="/dashboard" >
                    <span class="menu-side"><img src="assets/img/icon/menu-icon-01.svg" alt=""></span>
                    <span>Dashboard</span>
                </a>
            </li>
            <li>
                <a routerLink="/blank-chat" >
                   <span class="menu-side"><img src="assets/img/icon/menu-icon-02.svg" alt=""></span>
                    <span>Chats </span>
                </a>
            </li>
            <li>
                <a routerLink="/blank-channels" >
                   <span class="menu-side"><img src="assets/img/icon/menu-icon-03.svg" alt=""></span>
                    <span>Groups</span>
                </a>
            </li>
            <li>
                <a routerLink="blank-meet" class="active" >
                    <span class="menu-side"><img src="assets/img/icon/menu-icon-04.svg" alt=""></span>
                    <span>Calls</span>
                </a>
            </li>
        </ul>
    </div>
    <div class="top-nav-search mob-view">
        <form>
            <input type="text" class="form-control" placeholder="Find people, spaces, and messages">
            <a class="btn" ><i class="feather-search"></i></a>
        </form>
    </div>
    <ul class="nav user-menu-head float-end">
        <li class="nav-item dropdown d-none d-sm-block">
            <div class="book-view">
                <div class="book-dropdown">
                    <a href="javascript:void(0);" class="dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fas fa-circle me-2 green-status"></i> Active
                    </a>
                    <div class="dropdown-menu" >
                        <a class="dropdown-item" href="javascript:void(0);">
                            <i class="fas fa-circle me-2 green-status"></i> Active
                        </a>
                        <a class="dropdown-item" href="javascript:void(0);">
                            <i class="fas fa-circle me-2 red-status"></i> In Active
                        </a>
                    </div>
                </div>
            </div>
        </li>
        <li class="nav-item dropdown d-none d-sm-block">
            <a href="javascript:void(0);" class="dropdown-toggle nav-link bg-box" data-bs-toggle="dropdown"><img src="assets/img/icon/bell.svg" alt=""><span class="pulse"></span></a>
            <div class="dropdown-menu notifications">
                <div class="topnav-dropdown-header">
                    <span>Notifications</span>
                </div>
                <div class="drop-scroll">
                    <ul class="notification-list">
                        <li class="notification-message">
                            <a href="javascript:;">
                                <div class="media">
                                    <span class="note-users flex-shrink-0">
                                        <img alt="" src="assets/img/profiles/avatar-02.jpg" class="img-fluid">
                                    </span>
                                    <div class="media-body flex-grow-1">
                                        <p class="noti-details"><span class="noti-title">Patient appointment booking</span></p>
                                        <p class="noti-time"><span class="notification-time">4 mins ago</span></p>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="notification-message">
                            <a href="javascript:;">
                                <div class="media">
                                    <span class="note-users flex-shrink-0">
                                        <img alt="" src="assets/img/profiles/avatar-03.jpg" class="img-fluid">
                                    </span>
                                    <div class="media-body">
                                        <p class="noti-details"><span class="noti-title">Appointment booking with payment gateway</span></p>
                                        <p class="noti-time"><span class="notification-time">6 mins ago</span></p>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="notification-message">
                            <a href="javascript:;">
                                <div class="media">
                                    <span class="note-users flex-shrink-0">
                                        <img alt="" src="assets/img/profiles/avatar-04.jpg" class="img-fluid">
                                    </span>
                                    <div class="media-body">
                                        <p class="noti-details"><span class="noti-title">Doctor available module</span></p>
                                        <p class="noti-time"><span class="notification-time">8 mins ago</span></p>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="notification-message">
                            <a href="javascript:;">
                                <div class="media">
                                    <span class="note-users flex-shrink-0">
                                        <img alt="" src="assets/img/profiles/avatar-05.jpg" class="img-fluid">
                                    </span>
                                    <div class="media-body">
                                        <p class="noti-details"><span class="noti-title">Patient and Doctor video conferencing</span></p>
                                        <p class="noti-time"><span class="notification-time">12 mins ago</span></p>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="notification-message">
                            <a href="javascript:;">
                                <div class="media">
                                    <span class="note-users flex-shrink-0">
                                        <img alt="" src="assets/img/profiles/avatar-06.jpg" class="img-fluid">
                                    </span>
                                    <div class="media-body">
                                        <p class="noti-details"> <span class="noti-title">Private chat module</span></p>
                                        <p class="noti-time"><span class="notification-time">2 days ago</span></p>
                                    </div>
                                </div>
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="topnav-dropdown-footer">
                    <a href="javascript:void(0);">View all Notifications</a>
                </div>
            </div>
        </li>
        <li class="nav-item d-none d-sm-block">
            <a href="javascript:void(0);" id="dark-mode-toggle" class="bg-box"><img src="assets/img/icon/moon.svg" alt=""> </a>
        </li>
        <li class="nav-item dropdown has-arrow user-profile-list">
            <a href="javascript:void(0);" class="dropdown-toggle nav-link user-link" data-bs-toggle="dropdown">
                <span class="user-img">
                    <img  src="assets/img/profiles/avatar-01.jpg"  alt="Admin">
                </span>
            </a>
            <div class="dropdown-menu">
                <a class="dropdown-item" routerLink="/login">Logout</a>
            </div>
        </li>
    </ul>
    <div class="dropdown mobile-user-menu float-end">
        <a href="javascript:void(0);" class="dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false"><i class="fa-solid fa-ellipsis-vertical"></i></a>
        <div class="dropdown-menu dropdown-menu-end">
            <a class="dropdown-item" routerLink="/login">Logout</a>
        </div>
    </div>
</div>

<div class="sidebar" id="sidebar" (mouseover)="onMouseChange('mouseover')" (mouseout)="onMouseChange('mouseout')">
    <div class="sidebar-inner slimscroll">
        <perfect-scrollbar>
        <div id="sidebar-menu-one" class="sidebar-menu-one">
            <ul>
                <li class="chats-add">
                    <h4>Meetings<a href="javascript:;"><img src="assets/img/icon/refresh.svg" alt="img"></a></h4>
                </li>
                <li>
                    <div class="side-nav-search">
                        <form>
                            <input type="text" class="form-control" placeholder="Search here">
                            <a class="btn"><i class="feather-search"></i></a>
                        </form>
                    </div>
                </li>
                <li class="join-new-meet">
                    <a routerLink="/join-call"><span class="meet-new-icon"><img src="assets/img/icon/meet-icon-01.svg" alt="img"></span><span class="meet-text">New Meeting</span></a>
                </li>
                <li class="join-new-meet">
                    <a routerLink="/join-call"><span class="meet-new-icon"><img src="assets/img/icon/meet-icon-02.svg" alt="img"></span><span class="meet-text">Join a Meeting</span></a>
                </li>
                <li>
                    <div class="chat-user-actives active">
                        <a routerLink="/join-call" class="d-flex align-items-center">
                            <div class="chat-call-user meet-border">
                                <span class="letter-avatar"><img src="assets/img/icon/calendar.svg" alt="img"></span>
                            </div>
                            <div class="chat-users-recent">
                                <div class="recent-user-titles">
                                    <h5>Effective Forms Advertising...</h5>
                                    <p>It seems logical that the</p>
                                    <p>1:00 PM - 2:00 PM</p>
                                </div>
                            </div>
                        </a>
                    </div>
                </li>
                <li>
                    <div class="chat-user-actives">
                        <a routerLink="/join-call" class="d-flex align-items-center">
                            <div class="chat-call-user meet-border">
                                <span class="letter-avatar"><img src="assets/img/icon/calendar.svg" alt="img"></span>
                            </div>
                            <div class="chat-users-recent">
                                <div class="recent-user-titles">
                                    <h5>Get Best Advertising idea...</h5>
                                    <p>It seems logical that the</p>
                                    <p>1:00 PM - 2:00 PM</p>
                                </div>
                            </div>
                        </a>
                    </div>
                </li>
                <li>
                    <div class="chat-user-actives">
                        <a routerLink="/join-call" class="d-flex align-items-center">
                            <div class="chat-call-user meet-border">
                                <span class="letter-avatar"><img src="assets/img/icon/calendar.svg" alt="img"></span>
                            </div>
                            <div class="chat-users-recent">
                                <div class="recent-user-titles">
                                    <h5>Morning Status Call</h5>
                                    <p>It seems logical that the</p>
                                    <p>1:00 PM - 2:00 PM</p>
                                </div>
                            </div>
                        </a>
                    </div>
                </li>
                <li>
                    <div class="chat-user-actives">
                        <a routerLink="/join-call" class="d-flex align-items-center">
                            <div class="chat-call-user meet-border">
                                <span class="letter-avatar"><img src="assets/img/icon/calendar.svg" alt="img"></span>
                            </div>
                            <div class="chat-users-recent">
                                <div class="recent-user-titles">
                                    <h5>Evening EOD Call</h5>
                                    <p>It seems logical that the</p>
                                    <p>1:00 PM - 2:00 PM</p>
                                </div>
                            </div>
                        </a>
                    </div>
                </li>
                <li>
                    <div class="chat-user-actives">
                        <a routerLink="/join-call" class="d-flex align-items-center">
                            <div class="chat-call-user meet-border">
                                <span class="letter-avatar"><img src="assets/img/icon/calendar.svg" alt="img"></span>
                            </div>
                            <div class="chat-users-recent">
                                <div class="recent-user-titles">
                                    <h5>New Project Discussion</h5>
                                    <p>It seems logical that the</p>
                                    <p>1:00 PM - 2:00 PM</p>
                                </div>
                            </div>
                        </a>
                    </div>
                </li>
                <li>
                    <div class="chat-user-actives">
                        <a routerLink="/join-call" class="d-flex align-items-center">
                            <div class="chat-call-user meet-border">
                                <span class="letter-avatar"><img src="assets/img/icon/calendar.svg" alt="img"></span>
                            </div>
                            <div class="chat-users-recent">
                                <div class="recent-user-titles">
                                    <h5>Effective Forms Advertising...</h5>
                                    <p>It seems logical that the</p>
                                    <p>1:00 PM - 2:00 PM</p>
                                </div>
                            </div>
                        </a>
                    </div>
                </li>
                <li>
                    <div class="chat-user-actives">
                        <a routerLink="/join-call" class="d-flex align-items-center">
                            <div class="chat-call-user meet-border">
                                <span class="letter-avatar"><img src="assets/img/icon/calendar.svg" alt="img"></span>
                            </div>
                            <div class="chat-users-recent">
                                <div class="recent-user-titles">
                                    <h5>Get Best Advertising idea...</h5>
                                    <p>It seems logical that the</p>
                                    <p>1:00 PM - 2:00 PM</p>
                                </div>
                            </div>
                        </a>
                    </div>
                </li>
            </ul>
        </div>
    </perfect-scrollbar>
    </div>
</div>
<div class="page-wrapper-chat">
    <div class="content">
        <div class="row">
            <div class="col-xl-12">
                
                <!-- Chat -->
                <div class="card chat-empty card-comman">
                    <div class="card-body p-0">
                        <div class="chat-body meet-chat-blk">
                            <div class="join-call">
                                <div class="join-video">
                                    <img src="assets/img/video-call.jpg" class="img-fluid" alt="Logo">
                                    <div class="video-avatar"><h4>Camera is off</h4></div>
                                    <div class="call-icons">
                                        <ul class="call-items">
                                            <li class="call-item">
                                                <a class="mute-bt" href="javascript:void(0)" title="" data-bs-placement="top" data-bs-toggle="tooltip" data-bs-original-title="Mute Audio">
                                                    <i class="feather-mic"></i>
                                                </a>
                                            </li>
                                            <li class="call-item">
                                                <a class="mute-video" href="javascript:void(0)" title="" data-bs-placement="top" data-bs-toggle="tooltip" data-bs-original-title="Stop Camera">
                                                    <i class="feather-video"></i>
                                                </a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="join-content">
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="form-control-label">Morning Status Call</label>
                                            </div>
                                        </div>
                                    </div>
                                    <p>Enter a meeting nickname or the code provided by the meeting organizer</p>
                                    <div class="btn-infos">								
                                        <a routerLink="/meetingcall-horizontal" class="btn btn-primary btn-join">Join Now</a>
                                        <div class="d-flex align-items-center">
                                            <span class="icon-mic"><i class="feather-mic"></i></span> <span>Your microphone is working properly</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /Chat -->
                
            </div>
        </div>
    </div>
</div>

// vuejs-template/template-videocall/src/views/joincall.vue
<template>
    <!-- Main Wrapper -->
		<div class="main-wrapper">
            <layout-header1></layout-header1>
			
			<!-- Join Call -->
			<div class="page-content">
				<div class="join-call">
					<div class="join-video">
						<img src="../assets/img/video-call.jpg" class="img-fluid" alt="Logo">
						<div class="video-avatar"><h4>Camera is off</h4></div>
						<div class="call-icons">
							<ul class="call-items">
								<li class="call-item">
									<a class="mute-bt" title="" data-bs-placement="top" data-bs-toggle="tooltip" data-bs-original-title="Mute Audio">
										<i class="feather-mic"></i>
									</a>
								</li>
								<li class="call-item">
									<a class="mute-video" title="" data-bs-placement="top" data-bs-toggle="tooltip" data-bs-original-title="Stop Camera">
										<i class="feather-video"></i>
									</a>
								</li>
							</ul>
						</div>
					</div>
					<div class="join-content">
						<div class="row">
							<div class="col-md-6">
								<div class="form-group">
									<label class="form-control-label">What's your name?</label>
									<input type="text" class="form-control" placeholder="Enter Your Name here">
								</div>
							</div>
						</div>
						<h3>UX/UI Design Conference Meeting</h3>
						<div class="btn-infos">								
							<router-link to="/meeting-single-user" class="btn btn-primary btn-join">Join Now</router-link>
							<div class="d-flex align-items-center">
								<span class="icon-mic"><i class="feather-mic"></i></span> <span>Your microphone is working properly</span>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- /Join Call -->
			
		</div>
		<!-- /Main Wrapper -->
</template>

<script>
export default {
    mounted() {
        // Darkmode 
	
	if($('.toggle-switch').length > 0) {
		const toggleSwitch = document.querySelector('.toggle-switch input[type="checkbox"]');
		const currentTheme = localStorage.getItem('theme');
		var app = document.getElementsByTagName("BODY")[0];

		if (currentTheme) {
			app.setAttribute('data-theme', currentTheme);
		  
			if (currentTheme === 'dark') {
				toggleSwitch.checked = true;
			}
		}

		function switchTheme(e) {
			if (e.target.checked) {
				app.setAttribute('data-theme', 'dark');
				localStorage.setItem('theme', 'dark');
			}
			else {       
				app.setAttribute('data-theme', 'light');
				localStorage.setItem('theme', 'light');
			}    
		}

		toggleSwitch.addEventListener('change', switchTheme, false);	
	}
	
	if(window.location.hash == "#LightMode"){
		localStorage.setItem('theme', 'dark');
	}
	else {
		if(window.location.hash == "#DarkMode"){
			localStorage.setItem('theme', 'light');
		}
	}

	
	
	// Mute Audio
	
	if($('.mute-bt').length > 0) {
		$(".mute-bt").on('click', function(){
			if($(this).hasClass("stop")) {
				$(this).removeClass("stop");
				$(".mute-bt i").removeClass("feather-mic-off");
				$(".mute-bt i").addClass("feather-mic");
				$(this).attr("data-bs-original-title","Mute Audio");
				$(".join-video.user-active .more-icon").removeClass("mic-view");
				
				$(".action-info.vid-view li .mute-mic i").removeClass("feather-mic-off");
				$(".action-info.vid-view li .mute-mic i").addClass("feather-mic");
			}
			else{
				$(this).addClass("stop");
				$(".mute-bt i").removeClass("feather-mic");
				$(".mute-bt i").addClass("feather-mic-off");
				$(this).attr("data-bs-original-title","Unmute Audio");				
				$(".join-video.user-active .more-icon").addClass("mic-view");
				
				$(".add-list .user-active .action-info").addClass("vid-view");
				$(".action-info.vid-view li .mute-mic i").removeClass("feather-mic");
				$(".action-info.vid-view li .mute-mic i").addClass("feather-mic-off");
			}
		});
	}
	
	// Mute Video
	
	if($('.mute-video').length > 0) {
		$(".mute-video").on('click', function(){
			if($(this).hasClass("stop")) {
				$(this).removeClass("stop");
				$(".mute-video i").removeClass("feather-video-off");
				$(".mute-video i").addClass("feather-video");
				$(".join-call .join-video").removeClass("video-hide");
				$(".video-avatar").removeClass("active");
				$(this).attr("data-bs-original-title","Stop Camera");
				$(".meeting .join-video.user-active").removeClass("video-hide");
				
				$(".join-video.user-active .more-icon").removeClass("vid-view");				
				$(".action-info.vid-view li .mute-vid i").removeClass("feather-video-off");
				$(".action-info.vid-view li .mute-vid i").addClass("feather-video");
			}
			else{
				$(this).addClass("stop");
				$(".mute-video i").removeClass("feather-video");
				$(".mute-video i").addClass("feather-video-off");
				$(".join-call .join-video").addClass("video-hide");
				$(".video-avatar").addClass("active");
				$(this).attr("data-bs-original-title","Start Camera");
				$(".meeting .join-video.user-active").addClass("video-hide");
				
				$(".add-list .user-active .action-info").addClass("vid-view");
				$(".action-info.vid-view li .mute-vid i").removeClass("feather-video");
				$(".action-info.vid-view li .mute-vid i").addClass("feather-video-off");
			}
		});
	}
	
	// Record
	
	if($('.record-icon').length > 0) {
		$(".record-icon").on('click', function(){
			if($(".record-icon").hasClass("active")) {
				$(".record-icon").removeClass("active");
				$(".show-record").css("display", "none");
				$(".record-icon i").removeClass("far fa-stop-circle");
				$(".record-icon i").addClass("far fa-dot-circle");	
			}
			else {
				$(".record-icon").addClass("active");
				$(".show-record").css("display", "block");	
				$(".record-icon i").removeClass("far fa-dot-circle");
				$(".record-icon i").addClass("far fa-stop-circle");			
			}
		});
	}	
	
	// Handrise
	
	if($('.hand-raise').length > 0) {
		$(".hand-raise").on('click', function(){
			if($(this).hasClass("active")) {
				$(this).removeClass("active");
				$(".join-video.user-active .more-icon .handraise-on").removeClass("active");
			}
			else {
				$(this).addClass("active");
				$(".join-video.user-active .more-icon .handraise-on").addClass("active");				
			}
		});
	}	
	

	// Whiteboard
	if($('.whiteboard').length > 0) {
		$(".whiteboard").on('click', function(){
			if($(this).hasClass("active")) {
				$(this).removeClass("active");
				$(".join-contents.show-whiteboard").css("display", "none");	
				$(".join-contents.fade-whiteboard").css("display", "flex");	
			}
			else {
				$(this).addClass("active");						
				$(".join-contents.show-whiteboard").css("display", "flex");				
				$(".join-contents.fade-whiteboard").css("display", "none");		
				Painterro({
					id: 'my-holder' 
				}).show();					
			}
		});
	}
	
	// Chat
	
	var toggleChatList = 0;
	if($('.showChatList').length > 0) {
		$('.showChatList').on('click', function(e){
			e.preventDefault()
			if($('body').hasClass("show-invite-list")){
				$(".invite-sidebar-right").css("margin-right", "-100%");
				$('body').removeClass('show-invite-list');
				$('.showInviteList').removeClass('active');
				$(this).addClass('active');
				$('body').addClass('show-chat-list');
				$(".show-chat-list .user-sidebar-right").css("margin-right", "20px");
				toggleChatList=1;
				toggleInviteList=0;
			}
			else {
				if(toggleChatList==0) {
					toggleChatList=1;
					$(this).addClass('active');
					$('body').addClass('show-chat-list');
					$(".show-chat-list .user-sidebar-right").css("margin-right", "20px");
				}
				else {
					toggleChatList=0;
					$(this).removeClass('active');
					$('body').removeClass('show-chat-list');
					$(".user-sidebar-right").css("margin-right", "-100%");
				}
			}
		})
	}
		
	if($('#chatClose').length > 0) {
		$('#chatClose').on('click', function(e){
			e.preventDefault()		
			$('body').removeClass('show-chat-list');
			$('.showChatList').removeClass('active');
			$(".user-sidebar-right").css("margin-right", "-100%");
			toggleChatList=0;
		})
	}
		
	var toggleInviteList = 0;
	if($('.showInviteList').length > 0) {
		$('.showInviteList').on('click', function(e){
			e.preventDefault()
			if($('body').hasClass("show-chat-list")){
				$('body').removeClass('show-chat-list');
				$('.showChatList').removeClass('active');
				$(".user-sidebar-right").css("margin-right", "-100%");
				$(this).addClass('active');
				$('body').addClass('show-invite-list');
				$(".show-invite-list .invite-sidebar-right").css("margin-right", "20px");
				toggleInviteList=1;
				toggleChatList=0;
			}
			else {
				if(toggleInviteList==0) {
					toggleInviteList=1;
					$(this).addClass('active');
					$('body').addClass('show-invite-list');
					$(".show-invite-list .invite-sidebar-right").css("margin-right", "20px");
				}
				else {
					toggleInviteList=0;
					$(this).removeClass('active');
					$('body').removeClass('show-invite-list');
					$(".invite-sidebar-right").css("margin-right", "-100%");
				}
			}
		})
	}
		
	if($('#InviteClose').length > 0) {
		$('#InviteClose').on('click', function(e){
			e.preventDefault()		
			$('body').removeClass('show-invite-list');
			$(".invite-sidebar-right").css("margin-right", "-100%");
			$('.showInviteList').removeClass('active');
			toggleInviteList=0;
		})
	}
	
	if($('.win-maximize').length > 0) {
		$('.win-maximize').on('click', function(e){
			if (!document.fullscreenElement) {
				document.documentElement.requestFullscreen();
			} else {
				if (document.exitFullscreen) {
					document.exitFullscreen();
				}
			}
		})
	}

	// Chat

	var chatAppTarget = $('.chat-window');
	(function() {
		if ($(window).width() > 991)
			chatAppTarget.removeClass('chat-slide');
		
		$(document).on("click",".chat-window .chat-users-list a.media",function () {
			if ($(window).width() <= 991) {
				chatAppTarget.addClass('chat-slide');
			}
			return false;
		});
		$(document).on("click","#back_user_list",function () {
			if ($(window).width() <= 991) {
				chatAppTarget.removeClass('chat-slide');
			}	
			return false;
		});
	})();
	
	$(window).on('load',function(){
		$('.page-loading').fadeOut();
	});

	// Resize	

	function resizeInnerDiv() {
		
		var height = $(window).height();
		var screen_height = $(window).height() - 252;
		var screen_height_vertical_view = $(window).height() - 232;
		var screen_height_horizontal_view = $(window).height() - 292;

		
		$(".meeting-wrapper .join-contents").css("min-height", screen_height);
		$('.join-contents .join-video').css('height', (screen_height_horizontal_view / 4)*2.8);
		$('.join-contents .join-video img').css('height', (screen_height_horizontal_view / 4)*2.8);
		
		$('.join-contents .join-video.single-user img').css('height', screen_height / 4);
		$('.join-contents .join-video.single-user').css('height', screen_height / 4);
		$('.join-contents .join-video.single-user').css('min-height', screen_height / 4);
		
		$('.horizontal-view .join-video.single-user img').css('height', screen_height / 3);
		$('.horizontal-view .join-video.single-user').css('height', screen_height / 3);
		$('.horizontal-view .join-video.single-user').css('min-height', screen_height / 3);

		$('.grid-view .join-video.single-user img').css('height', screen_height / 2);
		$('.grid-view .join-video.single-user').css('height', screen_height / 2);
		$('.grid-view .join-video.single-user').css('min-height', screen_height / 2);

		$('.vertical-view .join-video').css('height', (screen_height_vertical_view / 4)*3);
		$('.vertical-view .join-video img').css('height', (screen_height_vertical_view / 4)*3);

		$('.vertical-view .join-video.single-user img').css('height', screen_height / 4);
		$('.vertical-view .join-video.single-user').css('height', screen_height / 4);
		$('.vertical-view .join-video.single-user').css('min-height', screen_height / 4);

		if($(window).width() < 768 ) {
			
			screen_height = $(window).height() - 232;
			screen_height_horizontal_view = $(window).height() - 232;

			$('.join-contents .join-video').css('height', screen_height_horizontal_view / 4);
			$('.join-contents .join-video img').css('height', screen_height_horizontal_view / 4);
			
			$('.join-contents .join-video.single-user img').css('height', screen_height / 4);
			$('.join-contents .join-video.single-user').css('height', screen_height / 4);
			$('.join-contents .join-video.single-user').css('min-height', screen_height / 4);
			
			$('.grid-view .join-video.single-user img').css('height', screen_height / 4);
			$('.grid-view .join-video.single-user').css('height', screen_height / 4);
			$('.grid-view .join-video.single-user').css('min-height', screen_height / 4);
			
			$('.vertical-view .join-video.single-user img').css('height', screen_height / 4);
			$('.vertical-view .join-video.single-user').css('height', screen_height / 4);
			$('.vertical-view .join-video.single-user').css('min-height', screen_height / 4);
		}
	}
		
	if($('.page-content').length > 0 ){
		resizeInnerDiv();
	}

	$(window).resize(function(){
		if($('.page-content').length > 0 ){
			resizeInnerDiv();
		}
	});

    }
}
</script>
