// angular-template/template-videocall/src/app/all-modules/meetingcall-grid/meetingcall-grid.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-meetingcall-grid',
  templateUrl: './meetingcall-grid.component.html',
  styleUrls: ['./meetingcall-grid.component.css']
})
export class MeetingcallGridComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
    var app = document.getElementsByTagName("BODY")[0];
    app.classList.remove("darkmode");
  }
  ngAfterViewInit() {
    this.loadpaintero("assets/plugins/painterro/painterro.min.js")
    this.loadjs("assets/js/script.js")
  }
  loadjs(js) {
    var script = document.createElement('script');
    script.src = js;
    script.async = false;
    document.body.appendChild(script);
  }
  loadpaintero(js) {
    var script = document.createElement('script');
    script.src = js;
    script.async = false;
    document.body.appendChild(script);
  }
}

<!-- Header -->
<header class="header fixed-position">
    <nav class="navbar navbar-expand-lg header-nav">
        <div class="navbar-header">
            <a routerLink="/dashboard" class="navbar-brand logo">
                <img src="assets/img/logo.png" class="img-fluid" alt="Logo">
            </a>
            <p>a2x3-x3pp-ca2i-extn</p>
        </div>
        <div class="main-menu-wrapper">
            <ul class="grid-menu">
                <li><a routerLink='/meetingcall-multigrid' class="tab-nav"><i class="fas fa-th"></i></a></li>
                <li><a routerLink='/meetingcall-vertical' class="tab-nav"><i class="fas fa-grip-vertical"></i></a></li>
                <li><a routerLink='/meetingcall-horizontal' class="tab-nav"><i class="fas fa-grip-horizontal"></i></a></li>
                <li class="active"><a routerLink='/meetingcall-grid' class="tab-nav"><i class="fas fa-th-large"></i></a></li>
                <li><a href="javascript:void(0);" class="tab-nav win-maximize"><i class="fas fa-expand-alt"></i></a></li>
            </ul>
        </div>
        <ul class="nav header-navbar-rht">						
            <li class="nav-item d-none d-sm-block">
                <a href="javascript:void(0);" id="dark-mode-call" class="call-box"><img src="assets/img/icon/moon.svg" alt=""> </a>
            </li>
            <li class="nav-item">
                <a href="javascript:void(0)" class="nav-link p-0">
                    <span class="user-img">
                        <img src="assets/img/user.jpg" alt="user">
                    </span>
                    <span class="user-name">Carl Kelly</span>
                </a>
            </li>
        </ul>
    </nav>
</header>
<!-- /Header -->
        
<!-- Join Call -->
<div class="page-content">
    <div class="meeting">
        <div class="meeting-wrapper">					
            <div class="meeting-list">
                
                <!-- Grid View -->
                <div class="join-contents grid-view fade-whiteboard">						
                    <div class="join-video user-active single-user">
                        <img src="assets/img/video-call.jpg" class="img-fluid" alt="Logo">
                        <div class="video-avatar">
                            <div class="text-avatar">
                                <div class="text-box">
                                    S
                                </div>
                            </div>
                        </div>
                        <div class="part-name">								
                            <h4>Shira</h4>
                        </div>									
                        <div class="more-icon">	
                            <a href="javascript:void(0)" class="handraise-on">
                                <i class="fas fa-hand-paper"></i>
                            </a>
                            <a href="javascript:void(0)" class="mic-off">
                                <i class="feather-mic-off"></i>
                            </a>
                        </div>
                        <div class="overlay-icon">	
                            <a href="javascript:void(0)">
                                <i class="fas fa-thumbtack"></i>
                            </a>	
                            <a href="javascript:void(0)">
                                <i class="feather-mic-off"></i>
                            </a>	
                            <a href="javascript:void(0)">
                                <i class="feather-minus-circle"></i>
                            </a>
                        </div>
                    </div>
                    <div class="join-video single-user">
                        <img src="assets/img/users/user-01.jpg" class="img-fluid" alt="Logo">
                        <div class="part-name">								
                            <h4>Saba G</h4>
                        </div>									
                        <div class="more-icon">	
                            <a href="javascript:void(0)">
                                <i class="feather-mic-off"></i>
                            </a>
                        </div>
                        <div class="overlay-icon">	
                            <a href="javascript:void(0)">
                                <i class="fas fa-thumbtack"></i>
                            </a>	
                            <a href="javascript:void(0)">
                                <i class="feather-mic-off"></i>
                            </a>	
                            <a href="javascript:void(0)">
                                <i class="feather-minus-circle"></i>
                            </a>
                        </div>
                    </div>
                    <div class="join-video single-user">
                        <img src="assets/img/users/user-02.jpg" class="img-fluid" alt="Logo">
                        <div class="part-name">								
                            <h4>Linnea</h4>
                        </div>
                        <div class="overlay-icon">	
                            <a href="javascript:void(0)">
                                <i class="fas fa-thumbtack"></i>
                            </a>	
                            <a href="javascript:void(0)">
                                <i class="feather-mic-off"></i>
                            </a>	
                            <a href="javascript:void(0)">
                                <i class="feather-minus-circle"></i>
                            </a>
                        </div>
                    </div>
                    <div class="join-video single-user">							
                        <div class="d-block">
                            <div class="text-avatar ripple">
                                <div class="text-box">
                                    A
                                </div>
                            </div>
                        </div>
                        <div class="part-name">								
                            <h4>Akshay</h4>
                        </div>									
                        <div class="more-icon">	
                            <a href="javascript:void(0)" class="">
                                <i class="feather-video-off"></i>
                            </a>
                            <a href="javascript:void(0)" class="handraise-on">
                                <i class="fas fa-hand-paper"></i>
                            </a>
                        </div>
                        <div class="overlay-icon">	
                            <a href="javascript:void(0)">
                                <i class="fas fa-thumbtack"></i>
                            </a>	
                            <a href="javascript:void(0)">
                                <i class="feather-mic-off"></i>
                            </a>
                            <a href="javascript:void(0)">
                                <i class="feather-minus-circle"></i>
                            </a>
                        </div>
                    </div>
                </div>
                <!-- /Grid View -->
                
                <!-- Whiteboard View -->
                <div class="join-contents vertical-view show-whiteboard">						
                    <div class="join-video user-active">
                        <div class="whiteboard-sec">
                            <div id='my-holder'></div> 
                        </div>
                    </div>
                    <div class="vertical-sec">
                        <div class="join-video single-user">
                            <img src="assets/img/users/user-01.jpg" class="img-fluid" alt="Logo">
                            <div class="part-name">								
                                <h4>Saba G</h4>
                            </div>									
                            <div class="more-icon">	
                                <a href="javascript:void(0)">
                                    <i class="feather-mic-off"></i>
                                </a>
                            </div>
                            <div class="overlay-icon">	
                                <a href="javascript:void(0)">
                                    <i class="fas fa-thumbtack"></i>
                                </a>	
                                <a href="javascript:void(0)">
                                    <i class="feather-mic-off"></i>
                                </a>	
                                <a href="javascript:void(0)">
                                    <i class="feather-minus-circle"></i>
                                </a>
                            </div>
                        </div>
                        <div class="join-video single-user">							
                            <div class="d-block">
                                <div class="text-avatar">
                                    <div class="text-box">
                                        L
                                    </div>
                                </div>
                            </div>
                            <div class="part-name">								
                                <h4>Linnea</h4>
                            </div>
                            <div class="overlay-icon">	
                                <a href="javascript:void(0)">
                                    <i class="fas fa-thumbtack"></i>
                                </a>	
                                <a href="javascript:void(0)">
                                    <i class="feather-mic-off"></i>
                                </a>	
                                <a href="javascript:void(0)">
                                    <i class="feather-minus-circle"></i>
                                </a>
                            </div>
                        </div>
                        <div class="join-video single-user">
                            <img src="assets/img/users/user-02.jpg" class="img-fluid" alt="Logo">
                            <div class="part-name">								
                                <h4>Elsie</h4>
                            </div>
                            <div class="overlay-icon">	
                                <a href="javascript:void(0)">
                                    <i class="fas fa-thumbtack"></i>
                                </a>	
                                <a href="javascript:void(0)">
                                    <i class="feather-mic-off"></i>
                                </a>	
                                <a href="javascript:void(0)">
                                    <i class="feather-minus-circle"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /Whiteboard View -->
                
            </div>
            
            <!-- Meet Footer -->
            <div class="meet-footer">
                <div class="meet-icons">	
                    <div class="view-more">	
                        <ul class="meet-items">
                            <li class="meet-item  dropdown dropdown-action">
                                <a href="javascript:void(0)" class="nav-link dropdown-toggle"  data-bs-toggle="dropdown" aria-expanded="false">
                                    <i class="feather-more-vertical"></i>
                                </a>
                                 <ul class="dropdown-menu settings-menu">
                                    <li><a class="dropdown-item showInviteList" href="javascript:void(0)"><i class="feather-user-plus"></i> Invite People</a></li>
                                    <li><a class="dropdown-item showChatList" href="javascript:void(0)"><i class="feather-message-circle"></i> Chat</a></li>
                                    <li><a class="dropdown-item whiteboard" href="javascript:void(0)"><i class="feather-edit-3"></i> Whiteboard</a></li>
                                    <li><a class="dropdown-item record-icon" href="javascript:void(0)"><i class="far fa-dot-circle"></i> Start Recording</a></li>
                                    <li><a class="dropdown-item" href="javascript:void(0)"><i class="feather-mic-off"></i> Mute Everyone</a></li>
                                    <li><a class="dropdown-item" href="javascript:void(0)"><i class="feather-camera-off"></i> Disable Everyone’s Camera</a></li>
                                    <li><a class="dropdown-item" href="javascript:void(0)"><i class="feather-youtube"></i> Share a Video</a></li>
                                    <li><a class="dropdown-item" href="javascript:void(0)"><i class="feather-settings"></i> Settings</a></li>
                                 </ul>
                            </li>
                        </ul>
                    </div>
                    <div class="met-icons">	
                        <ul class="meet-items">
                            <li class="meet-item  dropdown dropdown-action">
                                <a href="javascript:void(0)" class="nav-link dropdown-toggle"  data-bs-toggle="dropdown" aria-expanded="false">
                                    <i class="feather-settings"></i>
                                </a>
                                 <ul class="dropdown-menu settings-menu">
                                    <li><a class="dropdown-item" href="javascript:void(0)"><span class="user-img"><img src="assets/img/user.jpg" alt="user"> Carl Kelly</span></a></li>
                                    <li><a class="dropdown-item showInviteList" href="javascript:void(0)"><i class="feather-user-plus"></i> Invite People</a></li>
                                    <li><a class="dropdown-item  win-maximize" href="javascript:void(0)"><i class="feather-maximize"></i> View Full Screen</a></li>
                                    <li><a class="dropdown-item record-icon" href="javascript:void(0)"><i class="far fa-dot-circle"></i> Start Recording</a></li>
                                    <li><a class="dropdown-item" href="javascript:void(0)"><i class="feather-mic-off"></i> Mute Everyone</a></li>
                                    <li><a class="dropdown-item" href="javascript:void(0)"><i class="feather-camera-off"></i> Disable Everyone’s Camera</a></li>
                                    <li><a class="dropdown-item" href="javascript:void(0)"><i class="feather-youtube"></i> Share a Video</a></li>
                                    <li><a class="dropdown-item" href="javascript:void(0)"><i class="feather-settings"></i> Settings</a></li>
                                    <li><a class="dropdown-item" href="javascript:void(0)"><i class="feather-code"></i> Embed meeting</a></li>
                                 </ul>
                            </li>
                            <li class="meet-item">
                                <a href="javascript:void(0)" class="mute-video">
                                    <i class="feather-video"></i>
                                </a>
                            </li>
                            <li class="meet-item">
                                <a href="javascript:void(0)" class="mute-bt">
                                    <i class="feather-mic"></i>
                                </a>
                            </li>
                        </ul>	
                    </div>
                    <div class="action-icons">							
                        <ul class="action-items">
                            <li class="action-item">
                                <a routerLink='/join-call' class="callend-icon">
                                    <i class="material-icons">call_end</i>
                                </a>
                            </li>
                            <li class="action-item">
                                <a href="javascript:void(0)" class="share-icon">
                                    <i class="fas fa-share"></i>
                                </a>
                            </li>
                            <li class="action-item">
                                <a href="javascript:void(0)" class="record-icon">
                                    <i class="far fa-dot-circle"></i>
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div class="end-call">
                        <ul class="meet-items">
                            <li class="meet-item">
                                <a href="javascript:void(0)" class="hand-raise">
                                    <i class="fas fa-hand-paper"></i>
                                </a>
                            </li>
                            <li class="meet-item">
                                <a href="javascript:void(0)" class="showInviteList">
                                    <i class="feather-users"></i>
                                </a>
                            </li>
                            <li class="meet-item">
                                <a href="javascript:void(0)" class="whiteboard">
                                    <i class="feather-edit-3"></i>
                                </a>
                            </li>
                            <li class="meet-item">
                                <a href="javascript:void(0)" class="showChatList">
                                    <i class="feather-message-circle"></i>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- /Meet Footer -->
        </div>
    </div>
</div>
<!-- /Join Call -->

<!-- Record -->
<div class="show-record">
    <p><i class="far fa-dot-circle text-danger"></i> Recording<p>		
</div>
<!-- /Record -->

<!-- Chat Right -->
<div class="chat-cont-right user-sidebar-right">
    <div class="chat-header">
        <a href="javascript:void(0)" class="close-btn" id="chatClose">
            <i class="feather-x"></i>
        </a>
    </div>
    <div class="message-body">
        <div class="chat-body">
            <div class="chat-scroll">
                <ul class="list-unstyled">
                    <li class="media received">
                        <div class="avatar">
                            <img src="assets/img/users/user-02.jpg" alt="User Image" class="avatar-img">
                        </div>
                        <div class="media-body">
                            <div class="msg-box">															
                                <ul class="chat-msg-info">
                                    <li>
                                        <div class="chat-time">
                                            Linnea <span>8:35 AM</span>
                                        </div>
                                    </li>
                                </ul>
                                <div>
                                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry</p>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li class="media received">
                        <div class="avatar">
                            <img src="assets/img/users/user-01.jpg" alt="User Image" class="avatar-img">
                        </div>
                        <div class="media-body">
                            <div class="msg-box">
                                <ul class="chat-msg-info">
                                    <li>
                                        <div class="chat-time">
                                            Saba G <span>12:00 PM</span>
                                        </div>
                                    </li>
                                </ul>
                                <div>
                                    <p>Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. </p>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li class="media received">
                        <div class="avatar person-view">
                            A
                        </div>
                        <div class="media-body">
                            <div class="msg-box">
                                <ul class="chat-msg-info">
                                    <li>
                                        <div class="chat-time">
                                            Akshay <span>12:00 PM</span>
                                        </div>
                                    </li>
                                </ul>
                                <div>
                                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry</p>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li class="media sent">
                        <div class="media-body">
                            <div class="msg-box">
                                <ul class="chat-msg-info">
                                    <li>
                                        <div class="chat-time">
                                            You <span>12:00 PM</span>
                                        </div>
                                    </li>
                                </ul>
                                <div>
                                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry</p>
                                </div>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
        <div class="chat-footer">
            <div class="input-group">
                <input type="text" class="input-msg-send form-control" placeholder="Type Message...">
                <div class="input-group-append">
                    <button type="button" class="btn msg-send-btn"><i class="fab fa-telegram-plane"></i></button>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /Chat Right -->

<!-- Invite People -->
<div class="chat-cont-right invite-sidebar-right">
    <div class="chat-header">
        <div class="heading-text">Invite Someone</div>
        <a href="javascript:void(0)" class="close-btn" id="InviteClose">
            <i class="feather-x"></i>
        </a>
    </div>
    <div class="message-body">
        <div class="chat-body">
            <div class="chat-scroll">
                <ul class="add-list">
                    <li class="add-listitem user-active">
                        <div class="person-info">
                            <img src="assets/img/video-call.jpg" alt="User Image" class="avatar-img">
                            <div class="person-name">Shira</div>
                        </div>
                        <div class="list-body">														
                            <ul class="action-info">
                                <li>
                                    <a href="javascript:void(0)" class="mute-vid">
                                        <i class="feather-video"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:void(0)" class="mute-mic voice-act">
                                        <i class="feather-mic"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </li>
                    <li class="add-listitem">
                        <div class="person-info">
                            <img src="assets/img/users/user-02.jpg" alt="User Image" class="avatar-img">
                            <div class="person-name">Linnea</div>
                        </div>
                        <div class="list-body">														
                            <ul class="action-info">
                                <li>
                                    <a href="javascript:void(0)" class="mute-vid">
                                        <i class="feather-video"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:void(0)" class="mute-mic">
                                        <i class="feather-mic"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </li>
                    <li class="add-listitem">
                        <div class="person-info">
                            <img src="assets/img/users/user-01.jpg" alt="User Image" class="avatar-img">
                            <div class="person-name">Saba G</div>
                        </div>
                        <div class="list-body">														
                            <ul class="action-info">
                                <li>
                                    <a href="javascript:void(0)" class="mute-vid">
                                        <i class="feather-video"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:void(0)" class="mute-mic">
                                        <i class="feather-mic"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </li>
                    <li class="add-listitem">
                        <div class="person-info">
                            <div class="person-view">A</div>
                            <div class="person-name">Akshay</div>
                        </div>
                        <div class="list-body">														
                            <ul class="action-info">
                                <li>
                                    <a href="javascript:void(0)" class="mute-vid text-primary">
                                        <i class="feather-video-off"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:void(0)" class="mute-mic">
                                        <i class="feather-mic"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
        <div class="chat-footer d-grid">
            <button type="button" class="btn heading-text">Invite Someone</button>
        </div>
    </div>
</div>
<!-- /Invite People -->

// vuejs-template/template-videocall/src/views/meetingcallgrid.vue
<template>
    <!-- Main Wrapper -->
		<div class="main-wrapper">
            <layout-header></layout-header>
			
			<!-- Join Call -->
			<div class="page-content">
				<div class="meeting">
					<div class="meeting-wrapper">					
						<div class="meeting-list">
							
							<!-- Grid View -->
							<div class="join-contents grid-view fade-whiteboard">						
								<div class="join-video user-active single-user">
									<img src="../assets/img/video-call.jpg" class="img-fluid" alt="Logo">
									<div class="video-avatar">
										<div class="text-avatar">
											<div class="text-box">
												S
											</div>
										</div>
									</div>
									<div class="part-name">								
										<h4>Shira</h4>
									</div>									
									<div class="more-icon">	
										<a class="handraise-on">
											<i class="fas fa-hand-paper"></i>
										</a>
										<a class="mic-off">
											<i class="feather-mic-off"></i>
										</a>
									</div>
									<div class="overlay-icon">	
										<a>
											<i class="fas fa-thumbtack"></i>
										</a>	
										<a>
											<i class="feather-mic-off"></i>
										</a>	
										<a>
											<i class="feather-minus-circle"></i>
										</a>
									</div>
								</div>
								<div class="join-video single-user">
									<img src="../assets/img/users/user-01.jpg" class="img-fluid" alt="Logo">
									<div class="part-name">								
										<h4>Saba G</h4>
									</div>									
									<div class="more-icon">	
										<a>
											<i class="feather-mic-off"></i>
										</a>
									</div>
									<div class="overlay-icon">	
										<a>
											<i class="fas fa-thumbtack"></i>
										</a>	
										<a>
											<i class="feather-mic-off"></i>
										</a>	
										<a>
											<i class="feather-minus-circle"></i>
										</a>
									</div>
								</div>
								<div class="join-video single-user">
									<img src="../assets/img/users/user-02.jpg" class="img-fluid" alt="Logo">
									<div class="part-name">								
										<h4>Linnea</h4>
									</div>
									<div class="overlay-icon">	
										<a>
											<i class="fas fa-thumbtack"></i>
										</a>	
										<a>
											<i class="feather-mic-off"></i>
										</a>	
										<a>
											<i class="feather-minus-circle"></i>
										</a>
									</div>
								</div>
								<div class="join-video single-user">							
									<div class="d-block">
										<div class="text-avatar ripple">
											<div class="text-box">
												A
											</div>
										</div>
									</div>
									<div class="part-name">								
										<h4>Akshay</h4>
									</div>									
									<div class="more-icon">	
										<a class="">
											<i class="feather-video-off"></i>
										</a>
										<a class="handraise-on">
											<i class="fas fa-hand-paper"></i>
										</a>
									</div>
									<div class="overlay-icon">	
										<a>
											<i class="fas fa-thumbtack"></i>
										</a>	
										<a>
											<i class="feather-mic-off"></i>
										</a>
										<a>
											<i class="feather-minus-circle"></i>
										</a>
									</div>
								</div>
							</div>
							<!-- /Grid View -->
							
							<!-- Whiteboard View -->
							<div class="join-contents vertical-view show-whiteboard">						
								<div class="join-video user-active">
									<div class="whiteboard-sec">
										<div id='my-holder'></div> 
									</div>
								</div>
								<div class="vertical-sec">
									<div class="join-video single-user">
										<img src="../assets/img/users/user-01.jpg" class="img-fluid" alt="Logo">
										<div class="part-name">								
											<h4>Saba G</h4>
										</div>									
										<div class="more-icon">	
											<a>
												<i class="feather-mic-off"></i>
											</a>
										</div>
										<div class="overlay-icon">	
											<a>
												<i class="fas fa-thumbtack"></i>
											</a>	
											<a>
												<i class="feather-mic-off"></i>
											</a>	
											<a>
												<i class="feather-minus-circle"></i>
											</a>
										</div>
									</div>
									<div class="join-video single-user">							
										<div class="d-block">
											<div class="text-avatar">
												<div class="text-box">
													L
												</div>
											</div>
										</div>
										<div class="part-name">								
											<h4>Linnea</h4>
										</div>
										<div class="overlay-icon">	
											<a>
												<i class="fas fa-thumbtack"></i>
											</a>	
											<a>
												<i class="feather-mic-off"></i>
											</a>	
											<a>
												<i class="feather-minus-circle"></i>
											</a>
										</div>
									</div>
									<div class="join-video single-user">
										<img src="../assets/img/users/user-02.jpg" class="img-fluid" alt="Logo">
										<div class="part-name">								
											<h4>Elsie</h4>
										</div>
										<div class="overlay-icon">	
											<a>
												<i class="fas fa-thumbtack"></i>
											</a>	
											<a>
												<i class="feather-mic-off"></i>
											</a>	
											<a>
												<i class="feather-minus-circle"></i>
											</a>
										</div>
									</div>
								</div>
							</div>
							<!-- /Whiteboard View -->
							
						</div>
						
						<!-- Meet Footer -->
						<div class="meet-footer">
							<div class="meet-icons">	
								<div class="view-more">	
									<ul class="meet-items">
										<li class="meet-item  dropdown dropdown-action">
											<a class="nav-link dropdown-toggle"  data-bs-toggle="dropdown" aria-expanded="false">
												<i class="feather-more-vertical"></i>
											</a>
											 <ul class="dropdown-menu settings-menu">
												<li><a class="dropdown-item showInviteList" href="javascript:void(0);"><i class="feather-user-plus"></i> Invite People</a></li>
												<li><a class="dropdown-item showChatList" href="javascript:void(0);"><i class="feather-message-circle"></i> Chat</a></li>
												<li><a class="dropdown-item whiteboard" href="javascript:void(0);"><i class="feather-edit-3"></i> Whiteboard</a></li>
												<li><a class="dropdown-item record-icon" href="javascript:void(0);"><i class="far fa-dot-circle"></i> Start Recording</a></li>
												<li><a class="dropdown-item" href="javascript:void(0);"><i class="feather-mic-off"></i> Mute Everyone</a></li>
												<li><a class="dropdown-item" href="javascript:void(0);"><i class="feather-camera-off"></i> Disable Everyone’s Camera</a></li>
												<li><a class="dropdown-item" href="javascript:void(0);"><i class="feather-youtube"></i> Share a Video</a></li>
												<li><a class="dropdown-item" href="javascript:void(0);"><i class="feather-settings"></i> Settings</a></li>
											 </ul>
										</li>
									</ul>
								</div>
								<div class="met-icons">	
									<ul class="meet-items">
										<li class="meet-item  dropdown dropdown-action">
											<a class="nav-link dropdown-toggle"  data-bs-toggle="dropdown" aria-expanded="false">
												<i class="feather-settings"></i>
											</a>
											 <ul class="dropdown-menu settings-menu">
												<li><a class="dropdown-item" href="javascript:void(0);"><span class="user-img"><img src="../assets/img/user.jpg" alt="user"> Carl Kelly</span></a></li>
												<li><a class="dropdown-item showInviteList" href="javascript:void(0);"><i class="feather-user-plus"></i> Invite People</a></li>
												<li><a class="dropdown-item  win-maximize" href="javascript:void(0);"><i class="feather-maximize"></i> View Full Screen</a></li>
												<li><a class="dropdown-item record-icon" href="javascript:void(0);"><i class="far fa-dot-circle"></i> Start Recording</a></li>
												<li><a class="dropdown-item" href="javascript:void(0);"><i class="feather-mic-off"></i> Mute Everyone</a></li>
												<li><a class="dropdown-item" href="javascript:void(0);"><i class="feather-camera-off"></i> Disable Everyone’s Camera</a></li>
												<li><a class="dropdown-item" href="javascript:void(0);"><i class="feather-youtube"></i> Share a Video</a></li>
												<li><a class="dropdown-item" href="javascript:void(0);"><i class="feather-settings"></i> Settings</a></li>
												<li><a class="dropdown-item" href="javascript:void(0);"><i class="feather-code"></i> Embed meeting</a></li>
											 </ul>
										</li>
										<li class="meet-item">
											<a class="mute-video">
												<i class="feather-video"></i>
											</a>
										</li>
										<li class="meet-item">
											<a class="mute-bt">
												<i class="feather-mic"></i>
											</a>
										</li>
									</ul>	
								</div>
								<div class="action-icons">							
									<ul class="action-items">
										<li class="action-item">
											<router-link to="/join-call" class="callend-icon">
												<i class="material-icons">call_end</i>
											</router-link>
										</li>
										<li class="action-item">
											<a class="share-icon">
												<i class="fas fa-share"></i>
											</a>
										</li>
										<li class="action-item">
											<a class="record-icon">
												<i class="far fa-dot-circle"></i>
											</a>
										</li>
									</ul>
								</div>
								<div class="end-call">
									<ul class="meet-items">
										<li class="meet-item">
											<a class="hand-raise">
												<i class="fas fa-hand-paper"></i>
											</a>
										</li>
										<li class="meet-item">
											<a class="showInviteList">
												<i class="feather-users"></i>
											</a>
										</li>
										<li class="meet-item">
											<a class="whiteboard">
												<i class="feather-edit-3"></i>
											</a>
										</li>
										<li class="meet-item">
											<a class="showChatList">
												<i class="feather-message-circle"></i>
											</a>
										</li>
									</ul>
								</div>
							</div>
						</div>
						<!-- /Meet Footer -->
					</div>
				</div>
			</div>
			<!-- /Join Call -->
			
			<!-- Record -->
			<div class="show-record">
				<p><i class="far fa-dot-circle text-danger"></i> Recording</p>		
			</div>
			<!-- /Record -->
			
			<!-- Chat Right -->
			<div class="chat-cont-right user-sidebar-right">
				<div class="chat-header">
					<a class="close-btn" id="chatClose">
						<i class="feather-x"></i>
					</a>
				</div>
				<div class="message-body">
					<div class="chat-body">
						<div class="chat-scroll">
							<ul class="list-unstyled">
								<li class="media received">
									<div class="avatar">
										<img src="../assets/img/users/user-02.jpg" alt="User Image" class="avatar-img">
									</div>
									<div class="media-body">
										<div class="msg-box">															
											<ul class="chat-msg-info">
												<li>
													<div class="chat-time">
														Linnea <span>8:35 AM</span>
													</div>
												</li>
											</ul>
											<div>
												<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry</p>
											</div>
										</div>
									</div>
								</li>
								<li class="media received">
									<div class="avatar">
										<img src="../assets/img/users/user-01.jpg" alt="User Image" class="avatar-img">
									</div>
									<div class="media-body">
										<div class="msg-box">
											<ul class="chat-msg-info">
												<li>
													<div class="chat-time">
														Saba G <span>12:00 PM</span>
													</div>
												</li>
											</ul>
											<div>
												<p>Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. </p>
											</div>
										</div>
									</div>
								</li>
								<li class="media received">
									<div class="avatar person-view">
										A
									</div>
									<div class="media-body">
										<div class="msg-box">
											<ul class="chat-msg-info">
												<li>
													<div class="chat-time">
														Akshay <span>12:00 PM</span>
													</div>
												</li>
											</ul>
											<div>
												<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry</p>
											</div>
										</div>
									</div>
								</li>
								<li class="media sent">
									<div class="media-body">
										<div class="msg-box">
											<ul class="chat-msg-info">
												<li>
													<div class="chat-time">
														You <span>12:00 PM</span>
													</div>
												</li>
											</ul>
											<div>
												<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry</p>
											</div>
										</div>
									</div>
								</li>
							</ul>
						</div>
					</div>
					<div class="chat-footer">
						<div class="input-group">
							<input type="text" class="input-msg-send form-control" placeholder="Type Message...">
							<div class="input-group-append">
								<button type="button" class="btn msg-send-btn"><i class="fab fa-telegram-plane"></i></button>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- /Chat Right -->
			
			<!-- Invite People -->
			<div class="chat-cont-right invite-sidebar-right">
				<div class="chat-header">
					<div class="heading-text">Invite Someone</div>
					<a class="close-btn" id="InviteClose">
						<i class="feather-x"></i>
					</a>
				</div>
				<div class="message-body">
					<div class="chat-body">
						<div class="chat-scroll">
							<ul class="add-list">
								<li class="add-listitem user-active">
									<div class="person-info">
										<img src="../assets/img/video-call.jpg" alt="User Image" class="avatar-img">
										<div class="person-name">Shira</div>
									</div>
									<div class="list-body">														
										<ul class="action-info">
											<li>
												<a class="mute-vid">
													<i class="feather-video"></i>
												</a>
											</li>
											<li>
												<a class="mute-mic voice-act">
													<i class="feather-mic"></i>
												</a>
											</li>
										</ul>
									</div>
								</li>
								<li class="add-listitem">
									<div class="person-info">
										<img src="../assets/img/users/user-02.jpg" alt="User Image" class="avatar-img">
										<div class="person-name">Linnea</div>
									</div>
									<div class="list-body">														
										<ul class="action-info">
											<li>
												<a class="mute-vid">
													<i class="feather-video"></i>
												</a>
											</li>
											<li>
												<a class="mute-mic">
													<i class="feather-mic"></i>
												</a>
											</li>
										</ul>
									</div>
								</li>
								<li class="add-listitem">
									<div class="person-info">
										<img src="../assets/img/users/user-01.jpg" alt="User Image" class="avatar-img">
										<div class="person-name">Saba G</div>
									</div>
									<div class="list-body">														
										<ul class="action-info">
											<li>
												<a class="mute-vid">
													<i class="feather-video"></i>
												</a>
											</li>
											<li>
												<a class="mute-mic">
													<i class="feather-mic"></i>
												</a>
											</li>
										</ul>
									</div>
								</li>
								<li class="add-listitem">
									<div class="person-info">
										<div class="person-view">A</div>
										<div class="person-name">Akshay</div>
									</div>
									<div class="list-body">														
										<ul class="action-info">
											<li>
												<a class="mute-vid text-primary">
													<i class="feather-video-off"></i>
												</a>
											</li>
											<li>
												<a class="mute-mic">
													<i class="feather-mic"></i>
												</a>
											</li>
										</ul>
									</div>
								</li>
							</ul>
						</div>
					</div>
					<div class="chat-footer d-grid">
						<button type="button" class="btn heading-text">Invite Someone</button>
					</div>
				</div>
			</div>
			<!-- /Invite People -->
			
		</div>
		<!-- /Main Wrapper -->
</template>

<script>
import Painterro from 'painterro'
export default {
 data() {
      return {
       
      }
    },
    mounted() {

    // Darkmode 
	
	if($('.toggle-switch').length > 0) {
		const toggleSwitch = document.querySelector('.toggle-switch input[type="checkbox"]');
		const currentTheme = localStorage.getItem('theme');
		var app = document.getElementsByTagName("BODY")[0];

		if (currentTheme) {
			app.setAttribute('data-theme', currentTheme);
		  
			if (currentTheme === 'dark') {
				toggleSwitch.checked = true;
			}
		}

		function switchTheme(e) {
			if (e.target.checked) {
				app.setAttribute('data-theme', 'dark');
				localStorage.setItem('theme', 'dark');
			}
			else {       
				app.setAttribute('data-theme', 'light');
				localStorage.setItem('theme', 'light');
			}    
		}

		toggleSwitch.addEventListener('change', switchTheme, false);	
	}
	
	if(window.location.hash == "#LightMode"){
		localStorage.setItem('theme', 'dark');
	}
	else {
		if(window.location.hash == "#DarkMode"){
			localStorage.setItem('theme', 'light');
		}
	}

	
	
	// Mute Audio
	
	if($('.mute-bt').length > 0) {
		$(".mute-bt").on('click', function(){
			if($(this).hasClass("stop")) {
				$(this).removeClass("stop");
				$(".mute-bt i").removeClass("feather-mic-off");
				$(".mute-bt i").addClass("feather-mic");
				$(this).attr("data-bs-original-title","Mute Audio");
				$(".join-video.user-active .more-icon").removeClass("mic-view");
				
				$(".action-info.vid-view li .mute-mic i").removeClass("feather-mic-off");
				$(".action-info.vid-view li .mute-mic i").addClass("feather-mic");
			}
			else{
				$(this).addClass("stop");
				$(".mute-bt i").removeClass("feather-mic");
				$(".mute-bt i").addClass("feather-mic-off");
				$(this).attr("data-bs-original-title","Unmute Audio");				
				$(".join-video.user-active .more-icon").addClass("mic-view");
				
				$(".add-list .user-active .action-info").addClass("vid-view");
				$(".action-info.vid-view li .mute-mic i").removeClass("feather-mic");
				$(".action-info.vid-view li .mute-mic i").addClass("feather-mic-off");
			}
		});
	}
	
	// Mute Video
	
	if($('.mute-video').length > 0) {
		$(".mute-video").on('click', function(){
			if($(this).hasClass("stop")) {
				$(this).removeClass("stop");
				$(".mute-video i").removeClass("feather-video-off");
				$(".mute-video i").addClass("feather-video");
				$(".join-call .join-video").removeClass("video-hide");
				$(".video-avatar").removeClass("active");
				$(this).attr("data-bs-original-title","Stop Camera");
				$(".meeting .join-video.user-active").removeClass("video-hide");
				
				$(".join-video.user-active .more-icon").removeClass("vid-view");				
				$(".action-info.vid-view li .mute-vid i").removeClass("feather-video-off");
				$(".action-info.vid-view li .mute-vid i").addClass("feather-video");
			}
			else{
				$(this).addClass("stop");
				$(".mute-video i").removeClass("feather-video");
				$(".mute-video i").addClass("feather-video-off");
				$(".join-call .join-video").addClass("video-hide");
				$(".video-avatar").addClass("active");
				$(this).attr("data-bs-original-title","Start Camera");
				$(".meeting .join-video.user-active").addClass("video-hide");
				
				$(".add-list .user-active .action-info").addClass("vid-view");
				$(".action-info.vid-view li .mute-vid i").removeClass("feather-video");
				$(".action-info.vid-view li .mute-vid i").addClass("feather-video-off");
			}
		});
	}
	
	// Record
	
	if($('.record-icon').length > 0) {
		$(".record-icon").on('click', function(){
			if($(".record-icon").hasClass("active")) {
				$(".record-icon").removeClass("active");
				$(".show-record").css("display", "none");
				$(".record-icon i").removeClass("far fa-stop-circle");
				$(".record-icon i").addClass("far fa-dot-circle");	
			}
			else {
				$(".record-icon").addClass("active");
				$(".show-record").css("display", "block");	
				$(".record-icon i").removeClass("far fa-dot-circle");
				$(".record-icon i").addClass("far fa-stop-circle");			
			}
		});
	}	
	
	// Handrise
	
	if($('.hand-raise').length > 0) {
		$(".hand-raise").on('click', function(){
			if($(this).hasClass("active")) {
				$(this).removeClass("active");
				$(".join-video.user-active .more-icon .handraise-on").removeClass("active");
			}
			else {
				$(this).addClass("active");
				$(".join-video.user-active .more-icon .handraise-on").addClass("active");				
			}
		});
	}	
	

	// Whiteboard
	if($('.whiteboard').length > 0) {
		$(".whiteboard").on('click', function(){
			if($(this).hasClass("active")) {
				$(this).removeClass("active");
				$(".join-contents.show-whiteboard").css("display", "none");	
				$(".join-contents.fade-whiteboard").css("display", "flex");	
			}
			else {
				$(this).addClass("active");						
				$(".join-contents.show-whiteboard").css("display", "flex");				
				$(".join-contents.fade-whiteboard").css("display", "none");		
				Painterro({
					id: 'my-holder' 
				}).show();					
			}
		});
	}
	
	// Chat
	
	var toggleChatList = 0;
	if($('.showChatList').length > 0) {
		$('.showChatList').on('click', function(e){
			e.preventDefault()
			if($('body').hasClass("show-invite-list")){
				$(".invite-sidebar-right").css("margin-right", "-100%");
				$('body').removeClass('show-invite-list');
				$('.showInviteList').removeClass('active');
				$(this).addClass('active');
				$('body').addClass('show-chat-list');
				$(".show-chat-list .user-sidebar-right").css("margin-right", "20px");
				toggleChatList=1;
				toggleInviteList=0;
			}
			else {
				if(toggleChatList==0) {
					toggleChatList=1;
					$(this).addClass('active');
					$('body').addClass('show-chat-list');
					$(".show-chat-list .user-sidebar-right").css("margin-right", "20px");
				}
				else {
					toggleChatList=0;
					$(this).removeClass('active');
					$('body').removeClass('show-chat-list');
					$(".user-sidebar-right").css("margin-right", "-100%");
				}
			}
		})
	}
		
	if($('#chatClose').length > 0) {
		$('#chatClose').on('click', function(e){
			e.preventDefault()		
			$('body').removeClass('show-chat-list');
			$('.showChatList').removeClass('active');
			$(".user-sidebar-right").css("margin-right", "-100%");
			toggleChatList=0;
		})
	}
		
	var toggleInviteList = 0;
	if($('.showInviteList').length > 0) {
		$('.showInviteList').on('click', function(e){
			e.preventDefault()
			if($('body').hasClass("show-chat-list")){
				$('body').removeClass('show-chat-list');
				$('.showChatList').removeClass('active');
				$(".user-sidebar-right").css("margin-right", "-100%");
				$(this).addClass('active');
				$('body').addClass('show-invite-list');
				$(".show-invite-list .invite-sidebar-right").css("margin-right", "20px");
				toggleInviteList=1;
				toggleChatList=0;
			}
			else {
				if(toggleInviteList==0) {
					toggleInviteList=1;
					$(this).addClass('active');
					$('body').addClass('show-invite-list');
					$(".show-invite-list .invite-sidebar-right").css("margin-right", "20px");
				}
				else {
					toggleInviteList=0;
					$(this).removeClass('active');
					$('body').removeClass('show-invite-list');
					$(".invite-sidebar-right").css("margin-right", "-100%");
				}
			}
		})
	}
		
	if($('#InviteClose').length > 0) {
		$('#InviteClose').on('click', function(e){
			e.preventDefault()		
			$('body').removeClass('show-invite-list');
			$(".invite-sidebar-right").css("margin-right", "-100%");
			$('.showInviteList').removeClass('active');
			toggleInviteList=0;
		})
	}
	
	if($('.win-maximize').length > 0) {
		$('.win-maximize').on('click', function(e){
			if (!document.fullscreenElement) {
				document.documentElement.requestFullscreen();
			} else {
				if (document.exitFullscreen) {
					document.exitFullscreen();
				}
			}
		})
	}

	// Chat

	var chatAppTarget = $('.chat-window');
	(function() {
		if ($(window).width() > 991)
			chatAppTarget.removeClass('chat-slide');
		
		$(document).on("click",".chat-window .chat-users-list a.media",function () {
			if ($(window).width() <= 991) {
				chatAppTarget.addClass('chat-slide');
			}
			return false;
		});
		$(document).on("click","#back_user_list",function () {
			if ($(window).width() <= 991) {
				chatAppTarget.removeClass('chat-slide');
			}	
			return false;
		});
	})();
	
	$(window).on('load',function(){
		$('.page-loading').fadeOut();
	});

	// Resize	

	function resizeInnerDiv() {
		
		var height = $(window).height();
		var screen_height = $(window).height() - 252;
		var screen_height_vertical_view = $(window).height() - 232;
		var screen_height_horizontal_view = $(window).height() - 292;

		
		$(".meeting-wrapper .join-contents").css("min-height", screen_height);
		$('.join-contents .join-video').css('height', (screen_height_horizontal_view / 4)*2.8);
		$('.join-contents .join-video img').css('height', (screen_height_horizontal_view / 4)*2.8);
		
		$('.join-contents .join-video.single-user img').css('height', screen_height / 4);
		$('.join-contents .join-video.single-user').css('height', screen_height / 4);
		$('.join-contents .join-video.single-user').css('min-height', screen_height / 4);
		
		$('.horizontal-view .join-video.single-user img').css('height', screen_height / 3);
		$('.horizontal-view .join-video.single-user').css('height', screen_height / 3);
		$('.horizontal-view .join-video.single-user').css('min-height', screen_height / 3);

		$('.grid-view .join-video.single-user img').css('height', screen_height / 2);
		$('.grid-view .join-video.single-user').css('height', screen_height / 2);
		$('.grid-view .join-video.single-user').css('min-height', screen_height / 2);

		$('.vertical-view .join-video').css('height', (screen_height_vertical_view / 4)*3);
		$('.vertical-view .join-video img').css('height', (screen_height_vertical_view / 4)*3);

		$('.vertical-view .join-video.single-user img').css('height', screen_height / 4);
		$('.vertical-view .join-video.single-user').css('height', screen_height / 4);
		$('.vertical-view .join-video.single-user').css('min-height', screen_height / 4);

		if($(window).width() < 768 ) {
			
			screen_height = $(window).height() - 232;
			screen_height_horizontal_view = $(window).height() - 232;

			$('.join-contents .join-video').css('height', screen_height_horizontal_view / 4);
			$('.join-contents .join-video img').css('height', screen_height_horizontal_view / 4);
			
			$('.join-contents .join-video.single-user img').css('height', screen_height / 4);
			$('.join-contents .join-video.single-user').css('height', screen_height / 4);
			$('.join-contents .join-video.single-user').css('min-height', screen_height / 4);
			
			$('.grid-view .join-video.single-user img').css('height', screen_height / 4);
			$('.grid-view .join-video.single-user').css('height', screen_height / 4);
			$('.grid-view .join-video.single-user').css('min-height', screen_height / 4);
			
			$('.vertical-view .join-video.single-user img').css('height', screen_height / 4);
			$('.vertical-view .join-video.single-user').css('height', screen_height / 4);
			$('.vertical-view .join-video.single-user').css('min-height', screen_height / 4);
		}
	}
		
	if($('.page-content').length > 0 ){
		resizeInnerDiv();
	}

	$(window).resize(function(){
		if($('.page-content').length > 0 ){
			resizeInnerDiv();
		}
	});

    }
}
</script>
