// reactjs-template/template/src/MainPage/login.jsx

import React, { Component } from 'react';
import { Link } from 'react-router-dom';
import {Logo} from '../imagepath'

class Login extends Component {
   render() {
      return ( 
        <div className="content align-items-center">
        <div className="container-fluid">
          <div className="row">
            <div className="col-md-8 offset-md-2">
              {/* Login Tab Content */}
              <div className="account-content">
                <div className="row align-items-center justify-content-center">
                  <div className="col-md-12 col-lg-6 login-right">
                    <div className="login-header">
                      {/* <h3>Login <br><span>Access to our Chat</span></h3> */}
                      <Link to="chat">
                        <img src={Logo} alt="" className="header_image" />
                      </Link>
                    </div>
                    <form>
                      <div className="form-group">
                        <label>Email</label>
                        <input className="form-control form-control-lg group_formcontrol" name="new-chat-title" type="email" placeholder="Enter your email" />
                      </div>
                      <div className="form-group">
                        <label htmlFor="new-chat-topic">Password</label>
                        <input className="form-control form-control-lg group_formcontrol" name="new-chat-topic" id="new-chat-topic" type="text" placeholder="Enter your password" />
                      </div>
                      <div className="pt-1">
                        <div className="text-center">
                          <button className="btn newgroup_create btn-block d-block w-100" type="button"><Link style={{color:"white"}} to="/chat">Login</Link></button>
                          <span className="forgot-link">
                            <Link to="/forgot-password" className="text-right">Forgot Password ?</Link>
                          </span>
                        </div>
                      </div>
                    </form>
                    <div className="login-or">
                      <span className="or-line" />
                      <span className="span-or">or</span>
                    </div>
                    <div className="row form-row social-login">
                      <div className="col-6">
                        <Link to="https://www.facebook.com" target="_blank" className="btn btn-facebook btn-block"><i className="fab fa-facebook-f mr-1" /> Login</Link>
                      </div>
                      <div className="col-6">
                        <Link to="https://mail.google.com" className="btn btn-google btn-block" target="_blank"><i className="fab fa-google mr-1" /> Login</Link>
                      </div>
                    </div>
                    <div className="text-center dont-have">Don’t have an account? <Link to="/register">Register</Link></div>
                  </div>
                </div>
              </div>
              {/* /Login Tab Content */}
            </div>
          </div>
        </div>
      </div>
      );
   }
}

export default Login;

// angular-template/template-videocall/src/app/all-modules/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {
  password: any;
  show = false;

  constructor(public router: Router) { }
  direction() {
    this.router.navigate(['/dashboard']);
  }
  ngOnInit(): void {
    this.password = 'password';
    var app = document.getElementsByTagName("BODY")[0];
    app.classList.remove("darkmode");
    app.classList.remove("darkcall");
  }

  onClick() {
    if (this.password === 'password') {
      this.password = 'text';
      this.show = true;
    } else {
      this.password = 'password';
      this.show = false;
    }
  }
}

<div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 col-xl-6 p-0">
                
                <!-- Login -->
                <div class="login-wrapper">
                    <div class="loginbox">
                        <div class="log-header">
                            <a href="javascript:void(0);" class="navbar-brand logo">
                                <img src="assets/img/logo.png" class="img-fluid" width="35" alt="Logo">
                                <span>Dreamschat</span>
                            </a>
                        </div>
                        <h1>Welcome to <span>Dreamschat</span> <br>Get’s Started</h1>
                        <div class="form-signin">
                            <div class="form-group">
                                <input type="email" class="form-control" value="admin@example.com">
                                <span class="profile-views"><img src="assets/img/icon/mail-icon.svg"  alt=""></span>
                            </div>
                            <div class="form-group">
                                <input [type]="password" class="form-control pass-input" value="password">
                                <span class="profile-views feather-eye toggle-password" (click)="onClick()" *ngIf="show"></span>
                                <span class="profile-views feather-eye-off toggle-password" (click)="onClick()" *ngIf="!show"></span>
                            </div>
                            <div class="form-group">
                                <a class="forgot-link" routerLink='/forgot-password'>Forgot Password ?</a>
                            </div>
                            <div class="d-grid">
                                <button class="btn btn-primary btn-signin" type="submit" (click)="direction()">Sign In</button>
                            </div>
                            <div class="dont-have">Don't have an account? <a routerLink='/register'>Register</a></div>
                            <div class="login-or">
                                <p class="span-or">or</p>
                            </div>
                            <!-- Social Login -->
                            <div class="social-login">
                                <a href="javascript:void(0);"><img src="assets/img/google.png" class="img-fluid" alt="Logo"></a>
                                <a href="javascript:void(0);"><img src="assets/img/fb.png" class="img-fluid" alt="Logo"></a>
                            </div>
                            <!-- /Social Login -->
                        </div>
                    </div>
                </div>
                <!-- /Login -->
                
            </div>
            
            <!-- Banner -->
            <div class="col-xl-6 login-bg">
                <div class="login-banner">
                </div>
            </div>
            <!-- /Banner -->
            
        </div>
    </div>
