// angular-template/template-videocall/src/app/all-modules/meeting-call2/meeting-call2.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-meeting-call2',
  templateUrl: './meeting-call2.component.html',
  styleUrls: ['./meeting-call2.component.css']
})
export class MeetingCall2Component implements OnInit {

  constructor() { }

  ngOnInit(): void {
    var app = document.getElementsByTagName("BODY")[0];
    app.classList.remove("darkmode");
  }
  ngAfterViewInit() {
    this.loadpaintero("assets/plugins/painterro/painterro.min.js")
    this.loadjs("assets/js/script.js")
  }
  loadjs(js) {
    var script = document.createElement('script');
    script.src = js;
    script.async = false;
    document.body.appendChild(script);
  }
  loadpaintero(js) {
    var script = document.createElement('script');
    script.src = js;
    script.async = false;
    document.body.appendChild(script);
  }
}

<!-- Header -->
<header class="header fixed-position">
    <nav class="navbar navbar-expand-lg header-nav">
        <div class="navbar-header">
            <a routerLink="/dashboard" class="navbar-brand logo">
                <img src="assets/img/logo.png" class="img-fluid" alt="Logo">
            </a>
            <p>a2x3-x3pp-ca2i-extn</p>
        </div>
        <div class="main-menu-wrapper">
            <ul class="grid-menu">
                <li><a routerLink='/meetingcall-multigrid' class="tab-nav"><i class="fas fa-th"></i></a></li>
                <li><a routerLink='/meetingcall-vertical' class="tab-nav"><i class="fas fa-grip-vertical"></i></a></li>
                <li class="active"><a routerLink='/meeting-call2' class="tab-nav"><i class="fas fa-grip-horizontal"></i></a></li>
                <li><a routerLink='/meetingcall-grid' class="tab-nav"><i class="fas fa-th-large"></i></a></li>
                <li><a href="javascript:void(0);" class="tab-nav win-maximize"><i class="fas fa-expand-alt"></i></a></li>
            </ul>
        </div>
        <ul class="nav header-navbar-rht">						
            <li class="nav-item d-none d-sm-block">
                <a href="javascript:void(0);" id="dark-mode-call" class="call-box"><img src="assets/img/icon/moon.svg" alt=""> </a>
            </li>
            <li class="nav-item">
                <a href="javascript:void(0)" class="nav-link p-0">
                    <span class="user-img">
                        <img src="assets/img/user.jpg" alt="user">
                    </span>
                    <span class="user-name">Carl Kelly</span>
                </a>
            </li>
        </ul>
    </nav>
</header>
<!-- /Header -->
        
<!-- Join Call -->
<div class="page-content">
    <div class="meeting">
        <div class="meeting-wrapper">
        
            <div class="join-contents horizontal-view fade-whiteboard">						
                <div class="join-video user-active">
                    <img src="assets/img/video-call.jpg" class="img-fluid" alt="Logo">
                    <div class="video-avatar">
                        <div class="text-avatar">
                            <div class="text-box">
                                S
                            </div>
                        </div>
                        </div>
                    <div class="part-name">								
                        <h4>Shira</h4>
                    </div>									
                    <div class="more-icon">	
                        <a href="javascript:void(0)" class="handraise-on">
                            <i class="fas fa-hand-paper"></i>
                        </a>
                        <a href="javascript:void(0)" class="mic-on">
                            <i class="feather-more-horizontal"></i>
                        </a>
                        <a href="javascript:void(0)" class="mic-off">
                            <i class="feather-mic-off"></i>
                        </a>
                    </div>
                    <div class="overlay-icon">	
                        <a href="javascript:void(0)">
                            <i class="fas fa-thumbtack"></i>
                        </a>	
                        <a href="javascript:void(0)">
                            <i class="feather-mic-off"></i>
                        </a>	
                        <a href="javascript:void(0)">
                            <i class="feather-minus-circle"></i>
                        </a>
                    </div>
                </div>
                <div class="join-video single-user">
                    <img src="assets/img/users/user-01.jpg" class="img-fluid" alt="Logo">
                    <div class="part-name">								
                        <h4>Saba G</h4>
                    </div>									
                    <div class="more-icon">	
                        <a href="javascript:void(0)">
                            <i class="feather-mic-off"></i>
                        </a>
                    </div>
                    <div class="overlay-icon">	
                        <a href="javascript:void(0)">
                            <i class="fas fa-thumbtack"></i>
                        </a>	
                        <a href="javascript:void(0)">
                            <i class="feather-mic-off"></i>
                        </a>	
                        <a href="javascript:void(0)">
                            <i class="feather-minus-circle"></i>
                        </a>
                    </div>
                </div>
                <div class="join-video single-user">							
                    <div class="d-block">
                        <div class="text-avatar">
                            <div class="text-box">
                                L
                            </div>
                        </div>
                    </div>
                    <div class="part-name">								
                        <h4>Linnea</h4>
                    </div>									
                    <div class="more-icon">	
                        <a href="javascript:void(0)">
                            <i class="feather-more-horizontal"></i>
                        </a>
                    </div>
                    <div class="overlay-icon">	
                        <a href="javascript:void(0)">
                            <i class="fas fa-thumbtack"></i>
                        </a>	
                        <a href="javascript:void(0)">
                            <i class="feather-mic-off"></i>
                        </a>	
                        <a href="javascript:void(0)">
                            <i class="feather-minus-circle"></i>
                        </a>
                    </div>
                </div>
                <div class="join-video single-user">
                    <img src="assets/img/users/user-02.jpg" class="img-fluid" alt="Logo">
                    <div class="part-name">								
                        <h4>Elsie</h4>
                    </div>									
                    
                    <div class="more-icon">	
                        <a href="javascript:void(0)">
                            <i class="feather-more-horizontal"></i>
                        </a>
                    </div>
                    <div class="overlay-icon">	
                        <a href="javascript:void(0)">
                            <i class="fas fa-thumbtack"></i>
                        </a>	
                        <a href="javascript:void(0)">
                            <i class="feather-mic-off"></i>
                        </a>	
                        <a href="javascript:void(0)">
                            <i class="feather-minus-circle"></i>
                        </a>
                    </div>
                </div>
                <div class="join-video single-user">								
                    <div class="text-avatar">
                        <h4>+15</h4>
                    </div>
                </div>
            </div>
            
            <!-- Whiteboard View -->
            <div class="join-contents vertical-view show-whiteboard">						
                <div class="join-video user-active">
                    <div class="whiteboard-sec">
                        <div id='my-holder'></div> 
                    </div>
                </div>
                <div class="vertical-sec">
                    <div class="join-video single-user">
                        <img src="assets/img/users/user-01.jpg" class="img-fluid" alt="Logo">
                        <div class="part-name">								
                            <h4>Saba G</h4>
                        </div>									
                        <div class="more-icon">	
                            <a href="javascript:void(0)">
                                <i class="feather-mic-off"></i>
                            </a>
                        </div>
                        <div class="overlay-icon">	
                            <a href="javascript:void(0)">
                                <i class="fas fa-thumbtack"></i>
                            </a>	
                            <a href="javascript:void(0)">
                                <i class="feather-mic-off"></i>
                            </a>	
                            <a href="javascript:void(0)">
                                <i class="feather-minus-circle"></i>
                            </a>
                        </div>
                    </div>
                    <div class="join-video single-user">							
                        <div class="d-block">
                            <div class="text-avatar">
                                <div class="text-box">
                                    L
                                </div>
                            </div>
                        </div>
                        <div class="part-name">								
                            <h4>Linnea</h4>
                        </div>									
                        <div class="more-icon">	
                            <a href="javascript:void(0)">
                                <i class="feather-more-horizontal"></i>
                            </a>
                        </div>
                        <div class="overlay-icon">	
                            <a href="javascript:void(0)">
                                <i class="fas fa-thumbtack"></i>
                            </a>	
                            <a href="javascript:void(0)">
                                <i class="feather-mic-off"></i>
                            </a>	
                            <a href="javascript:void(0)">
                                <i class="feather-minus-circle"></i>
                            </a>
                        </div>
                    </div>
                    <div class="join-video single-user">
                        <img src="assets/img/users/user-02.jpg" class="img-fluid" alt="Logo">
                        <div class="part-name">								
                            <h4>Elsie</h4>
                        </div>									
                        <div class="more-icon">	
                            <a href="javascript:void(0)">
                                <i class="feather-more-horizontal"></i>
                            </a>
                        </div>
                        <div class="overlay-icon">	
                            <a href="javascript:void(0)">
                                <i class="fas fa-thumbtack"></i>
                            </a>	
                            <a href="javascript:void(0)">
                                <i class="feather-mic-off"></i>
                            </a>	
                            <a href="javascript:void(0)">
                                <i class="feather-minus-circle"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /Whiteboard View -->	
            
            <!-- Meet Footer -->
            <div class="meet-footer">
                <div class="meet-icons">	
                    <div class="view-more">	
                        <ul class="meet-items">
                            <li class="meet-item  dropdown dropdown-action">
                                <a href="javascript:void(0)" class="nav-link dropdown-toggle"  data-bs-toggle="dropdown" aria-expanded="false">
                                    <i class="feather-more-vertical"></i>
                                </a>
                                 <ul class="dropdown-menu settings-menu">
                                    <li><a class="dropdown-item showInviteList" href="javascript:void(0)"><i class="feather-user-plus"></i> Invite People</a></li>
                                    <li><a class="dropdown-item showChatList" href="javascript:void(0)"><i class="feather-message-circle"></i> Chat</a></li>
                                    <li><a class="dropdown-item whiteboard" href="javascript:void(0)"><i class="feather-edit-3"></i> Whiteboard</a></li>
                                    <li><a class="dropdown-item record-icon" href="javascript:void(0)"><i class="far fa-dot-circle"></i> Start Recording</a></li>
                                    <li><a class="dropdown-item" href="javascript:void(0)"><i class="feather-mic-off"></i> Mute Everyone</a></li>
                                    <li><a class="dropdown-item" href="javascript:void(0)"><i class="feather-camera-off"></i> Disable Everyone’s Camera</a></li>
                                    <li><a class="dropdown-item" href="javascript:void(0)"><i class="feather-youtube"></i> Share a Video</a></li>
                                    <li><a class="dropdown-item" href="javascript:void(0)"><i class="feather-settings"></i> Settings</a></li>
                                 </ul>
                            </li>
                        </ul>
                    </div>
                    <div class="met-icons">	
                        <ul class="meet-items">
                            <li class="meet-item  dropdown dropdown-action">
                                <a href="javascript:void(0)" class="nav-link dropdown-toggle"  data-bs-toggle="dropdown" aria-expanded="false">
                                    <i class="feather-settings"></i>
                                </a>
                                 <ul class="dropdown-menu settings-menu">
                                    <li><a class="dropdown-item" href="javascript:void(0)"><span class="user-img"><img src="assets/img/user.jpg" alt="user"> Carl Kelly</span></a></li>
                                    <li><a class="dropdown-item showInviteList" href="javascript:void(0)"><i class="feather-user-plus"></i> Invite People</a></li>
                                    <li><a class="dropdown-item" href="javascript:void(0)"><i class="feather-maximize"></i> View Full Screen</a></li>
                                    <li><a class="dropdown-item record-icon" href="javascript:void(0)"><i class="far fa-dot-circle"></i> Start Recording</a></li>
                                    <li><a class="dropdown-item" href="javascript:void(0)"><i class="feather-mic-off"></i> Mute Everyone</a></li>
                                    <li><a class="dropdown-item" href="javascript:void(0)"><i class="feather-camera-off"></i> Disable Everyone’s Camera</a></li>
                                    <li><a class="dropdown-item" href="javascript:void(0)"><i class="feather-youtube"></i> Share a Video</a></li>
                                    <li><a class="dropdown-item" href="javascript:void(0)"><i class="feather-settings"></i> Settings</a></li>
                                    <li><a class="dropdown-item" href="javascript:void(0)"><i class="feather-code"></i> Embed meeting</a></li>
                                 </ul>
                            </li>
                            <li class="meet-item">
                                <a href="javascript:void(0)" class="mute-video">
                                    <i class="feather-video"></i>
                                </a>
                            </li>
                            <li class="meet-item">
                                <a href="javascript:void(0)" class="mute-bt">
                                    <i class="feather-mic"></i>
                                </a>
                            </li>
                        </ul>	
                    </div>
                    <div class="action-icons">							
                        <ul class="action-items">
                            <li class="action-item">
                                <a routerLink='/join-call' class="callend-icon">
                                    <i class="material-icons">call_end</i>
                                </a>
                            </li>
                            <li class="action-item">
                                <a href="javascript:void(0)" class="share-icon">
                                    <i class="fas fa-share"></i>
                                </a>
                            </li>
                            <li class="action-item">
                                <a href="javascript:void(0)" class="record-icon">
                                    <i class="far fa-dot-circle"></i>
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div class="end-call">
                        <ul class="meet-items">
                            <li class="meet-item">
                                <a href="javascript:void(0)" class="hand-raise">
                                    <i class="fas fa-hand-paper"></i>
                                </a>
                            </li>
                            <li class="meet-item">
                                <a href="javascript:void(0)" class="showInviteList">
                                    <i class="feather-users"></i>
                                </a>
                            </li>
                            <li class="meet-item">
                                <a href="javascript:void(0)" class="whiteboard">
                                    <i class="feather-edit-3"></i>
                                </a>
                            </li>
                            <li class="meet-item">
                                <a href="javascript:void(0)" class="showChatList">
                                    <i class="feather-message-circle"></i>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- /Meet Footer -->
            
        </div>
    </div>
</div>
<!-- /Join Call -->

<!-- Record -->
<div class="show-record">
    <p><i class="far fa-dot-circle text-danger"></i> Recording<p>		
</div>
<!-- /Record -->

<!-- Chat Right -->
<div class="chat-cont-right user-sidebar-right">
    <div class="chat-header">
        <a href="javascript:void(0)" class="close-btn" id="chatClose">
            <i class="feather-x"></i>
        </a>
    </div>
    <div class="message-body">
        <div class="chat-body">
            <div class="chat-scroll">
                <ul class="list-unstyled">
                    <li class="media received">
                        <div class="avatar">
                            <img src="assets/img/users/user-02.jpg" alt="User Image" class="avatar-img">
                        </div>
                        <div class="media-body">
                            <div class="msg-box">															
                                <ul class="chat-msg-info">
                                    <li>
                                        <div class="chat-time">
                                            Linnea <span>8:35 AM</span>
                                        </div>
                                    </li>
                                </ul>
                                <div>
                                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry</p>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li class="media received">
                        <div class="avatar">
                            <img src="assets/img/users/user-01.jpg" alt="User Image" class="avatar-img">
                        </div>
                        <div class="media-body">
                            <div class="msg-box">
                                <ul class="chat-msg-info">
                                    <li>
                                        <div class="chat-time">
                                            Saba G <span>12:00 PM</span>
                                        </div>
                                    </li>
                                </ul>
                                <div>
                                    <p>Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. </p>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li class="media received">
                        <div class="avatar person-view">
                            A
                        </div>
                        <div class="media-body">
                            <div class="msg-box">
                                <ul class="chat-msg-info">
                                    <li>
                                        <div class="chat-time">
                                            Akshay <span>12:00 PM</span>
                                        </div>
                                    </li>
                                </ul>
                                <div>
                                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry</p>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li class="media sent">
                        <div class="media-body">
                            <div class="msg-box">
                                <ul class="chat-msg-info">
                                    <li>
                                        <div class="chat-time">
                                            You <span>12:00 PM</span>
                                        </div>
                                    </li>
                                </ul>
                                <div>
                                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry</p>
                                </div>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
        <div class="chat-footer">
            <div class="input-group">
                <input type="text" class="input-msg-send form-control" placeholder="Type Message...">
                <div class="input-group-append">
                    <button type="button" class="btn msg-send-btn"><i class="fab fa-telegram-plane"></i></button>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /Chat Right -->

<!-- Invite People -->
<div class="chat-cont-right invite-sidebar-right">
    <div class="chat-header">
        <div class="heading-text">Invite Someone</div>
        <a href="javascript:void(0)" class="close-btn" id="InviteClose">
            <i class="feather-x"></i>
        </a>
    </div>
    <div class="message-body">
        <div class="chat-body">
            <div class="chat-scroll">
                <ul class="add-list">
                    <li class="add-listitem user-active">
                        <div class="person-info">
                            <img src="assets/img/video-call.jpg" alt="User Image" class="avatar-img">
                            <div class="person-name">Shira</div>
                        </div>
                        <div class="list-body">														
                            <ul class="action-info">
                                <li>
                                    <a href="javascript:void(0)" class="mute-vid">
                                        <i class="feather-video"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:void(0)" class="mute-mic">
                                        <i class="feather-mic"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </li>
                    <li class="add-listitem">
                        <div class="person-info">
                            <img src="assets/img/users/user-02.jpg" alt="User Image" class="avatar-img">
                            <div class="person-name">Linnea</div>
                        </div>
                        <div class="list-body">														
                            <ul class="action-info">
                                <li>
                                    <a href="javascript:void(0)" class="mute-vid">
                                        <i class="feather-video"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:void(0)" class="mute-mic">
                                        <i class="feather-mic"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </li>
                    <li class="add-listitem">
                        <div class="person-info">
                            <img src="assets/img/users/user-01.jpg" alt="User Image" class="avatar-img">
                            <div class="person-name">Saba G</div>
                        </div>
                        <div class="list-body">														
                            <ul class="action-info">
                                <li>
                                    <a href="javascript:void(0)" class="mute-vid">
                                        <i class="feather-video"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:void(0)" class="mute-mic">
                                        <i class="feather-mic"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </li>
                    <li class="add-listitem">
                        <div class="person-info">
                            <div class="person-view">A</div>
                            <div class="person-name">Akshay</div>
                        </div>
                        <div class="list-body">														
                            <ul class="action-info">
                                <li>
                                    <a href="javascript:void(0)" class="mute-vid text-primary">
                                        <i class="feather-video-off"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:void(0)" class="mute-mic">
                                        <i class="feather-mic"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
        <div class="chat-footer d-grid">
            <button type="button" class="btn heading-text">Invite Someone</button>
        </div>
    </div>
</div>
<!-- /Invite People -->

// reactjs-template/template-videocall/src/components/meetingcall2/index.jsx
import React from "react";
import { Link } from "react-router-dom";
import Header from "../header";
import Footer from "../footer";

// Import Images
import { user01, user02, Videocall } from "../imagepath";

    const Meetingcall2 = () => {
   
        return (
          <>
          {/* Main Wrapper */}
          <div className="main-wrapper">
            <Header/>
            {/* Join Call */}
            <div className="page-content">
              <div className="meeting">
                <div className="meeting-wrapper">
                  <div className="join-contents horizontal-view fade-whiteboard">
                    <div className="join-video user-active">
                      <img
                        src={Videocall}
                        className="img-fluid"
                        alt="Logo"
                      />
                      <div className="video-avatar">
                        <div className="text-avatar">
                          <div className="text-box">S</div>
                        </div>
                      </div>
                      <div className="part-name">
                        <h4>Shira</h4>
                      </div>
                      <div className="more-icon">
                        <a href="#" className="handraise-on">
                          <i className="fas fa-hand-paper" />
                        </a>
                        <a href="#" className="mic-on">
                          <i className="feather-more-horizontal" />
                        </a>
                        <a href="#" className="mic-off">
                          <i className="feather-mic-off" />
                        </a>
                      </div>
                      <div className="overlay-icon">
                        <a href="#">
                          <i className="fas fa-thumbtack" />
                        </a>
                        <a href="#">
                          <i className="feather-mic-off" />
                        </a>
                        <a href="#">
                          <i className="feather-minus-circle" />
                        </a>
                      </div>
                    </div>
                    <div className="join-video single-user">
                      <img
                        src={user01}
                        className="img-fluid"
                        alt="Logo"
                      />
                      <div className="part-name">
                        <h4>Saba G</h4>
                      </div>
                      <div className="more-icon">
                        <a href="#">
                          <i className="feather-mic-off" />
                        </a>
                      </div>
                      <div className="overlay-icon">
                        <a href="#">
                          <i className="fas fa-thumbtack" />
                        </a>
                        <a href="#">
                          <i className="feather-mic-off" />
                        </a>
                        <a href="#">
                          <i className="feather-minus-circle" />
                        </a>
                      </div>
                    </div>
                    <div className="join-video single-user">
                      <div className="d-block">
                        <div className="text-avatar">
                          <div className="text-box">L</div>
                        </div>
                      </div>
                      <div className="part-name">
                        <h4>Linnea</h4>
                      </div>
                      <div className="more-icon">
                        <a href="#">
                          <i className="feather-more-horizontal" />
                        </a>
                      </div>
                      <div className="overlay-icon">
                        <a href="#">
                          <i className="fas fa-thumbtack" />
                        </a>
                        <a href="#">
                          <i className="feather-mic-off" />
                        </a>
                        <a href="#">
                          <i className="feather-minus-circle" />
                        </a>
                      </div>
                    </div>
                    <div className="join-video single-user">
                      <img
                        src={user02}
                        className="img-fluid"
                        alt="Logo"
                      />
                      <div className="part-name">
                        <h4>Elsie</h4>
                      </div>
                      <div className="more-icon">
                        <a href="#">
                          <i className="feather-more-horizontal" />
                        </a>
                      </div>
                      <div className="overlay-icon">
                        <a href="#">
                          <i className="fas fa-thumbtack" />
                        </a>
                        <a href="#">
                          <i className="feather-mic-off" />
                        </a>
                        <a href="#">
                          <i className="feather-minus-circle" />
                        </a>
                      </div>
                    </div>
                    <div className="join-video single-user">
                      <div className="text-avatar">
                        <h4>+15</h4>
                      </div>
                    </div>
                  </div>
                  {/* Whiteboard View */}
                  <div className="join-contents vertical-view show-whiteboard">
                    <div className="join-video user-active">
                      <div className="whiteboard-sec">
                        <div id="my-holder" />
                      </div>
                    </div>
                    <div className="vertical-sec">
                      <div className="join-video single-user">
                        <img
                          src={user01}
                          className="img-fluid"
                          alt="Logo"
                        />
                        <div className="part-name">
                          <h4>Saba G</h4>
                        </div>
                        <div className="more-icon">
                          <a href="#">
                            <i className="feather-mic-off" />
                          </a>
                        </div>
                        <div className="overlay-icon">
                          <a href="#">
                            <i className="fas fa-thumbtack" />
                          </a>
                          <a href="#">
                            <i className="feather-mic-off" />
                          </a>
                          <a href="#">
                            <i className="feather-minus-circle" />
                          </a>
                        </div>
                      </div>
                      <div className="join-video single-user">
                        <div className="d-block">
                          <div className="text-avatar">
                            <div className="text-box">L</div>
                          </div>
                        </div>
                        <div className="part-name">
                          <h4>Linnea</h4>
                        </div>
                        <div className="more-icon">
                          <a href="#">
                            <i className="feather-more-horizontal" />
                          </a>
                        </div>
                        <div className="overlay-icon">
                          <a href="#">
                            <i className="fas fa-thumbtack" />
                          </a>
                          <a href="#">
                            <i className="feather-mic-off" />
                          </a>
                          <a href="#">
                            <i className="feather-minus-circle" />
                          </a>
                        </div>
                      </div>
                      <div className="join-video single-user">
                        <img
                          src={user02}
                          className="img-fluid"
                          alt="Logo"
                        />
                        <div className="part-name">
                          <h4>Elsie</h4>
                        </div>
                        <div className="more-icon">
                          <a href="#">
                            <i className="feather-more-horizontal" />
                          </a>
                        </div>
                        <div className="overlay-icon">
                          <a href="#">
                            <i className="fas fa-thumbtack" />
                          </a>
                          <a href="#">
                            <i className="feather-mic-off" />
                          </a>
                          <a href="#">
                            <i className="feather-minus-circle" />
                          </a>
                        </div>
                      </div>
                    </div>
                  </div>
                  {/* /Whiteboard View */}
                 <Footer/>
                </div>
              </div>
            </div>
            {/* /Join Call */}
             {/* Record */}
             <div className="show-record">
              <p>
                <i className="far fa-dot-circle text-danger" /> Recording
              </p>
              <p></p>
            </div>
            {/* /Record */}
            {/* Chat Right */}
            <div className="chat-cont-right user-sidebar-right">
              <div className="chat-header">
                <a href="#" className="close-btn" id="chatClose">
                  <i className="feather-x" />
                </a>
              </div>
              <div className="message-body">
                <div className="chat-body">
                  <div className="chat-scroll">
                    <ul className="list-unstyled">
                      <li className="media received">
                        <div className="avatar">
                          <img
                            src={user02}
                            alt="User Image"
                            className="avatar-img"
                          />
                        </div>
                        <div className="media-body">
                          <div className="msg-box">
                            <ul className="chat-msg-info">
                              <li>
                                <div className="chat-time">
                                  Linnea <span>8:35 AM</span>
                                </div>
                              </li>
                            </ul>
                            <div>
                              <p>
                                Lorem Ipsum is simply dummy text of the printing and
                                typesetting industry
                              </p>
                            </div>
                          </div>
                        </div>
                      </li>
                      <li className="media received">
                        <div className="avatar">
                          <img
                            src={user01}
                            alt="User Image"
                            className="avatar-img"
                          />
                        </div>
                        <div className="media-body">
                          <div className="msg-box">
                            <ul className="chat-msg-info">
                              <li>
                                <div className="chat-time">
                                  Saba G <span>12:00 PM</span>
                                </div>
                              </li>
                            </ul>
                            <div>
                              <p>
                                Lorem Ipsum has been the industry's standard dummy text
                                ever since the 1500s, when an unknown printer took a
                                galley of type and scrambled it to make a type specimen
                                book.{" "}
                              </p>
                            </div>
                          </div>
                        </div>
                      </li>
                      <li className="media received">
                        <div className="avatar person-view">A</div>
                        <div className="media-body">
                          <div className="msg-box">
                            <ul className="chat-msg-info">
                              <li>
                                <div className="chat-time">
                                  Akshay <span>12:00 PM</span>
                                </div>
                              </li>
                            </ul>
                            <div>
                              <p>
                                Lorem Ipsum is simply dummy text of the printing and
                                typesetting industry
                              </p>
                            </div>
                          </div>
                        </div>
                      </li>
                      <li className="media sent">
                        <div className="media-body">
                          <div className="msg-box">
                            <ul className="chat-msg-info">
                              <li>
                                <div className="chat-time">
                                  You <span>12:00 PM</span>
                                </div>
                              </li>
                            </ul>
                            <div>
                              <p>
                                Lorem Ipsum is simply dummy text of the printing and
                                typesetting industry
                              </p>
                            </div>
                          </div>
                        </div>
                      </li>
                    </ul>
                  </div>
                </div>
                <div className="chat-footer">
                  <div className="input-group">
                    <input
                      type="text"
                      className="input-msg-send form-control"
                      placeholder="Type Message..."
                    />
                    <div className="input-group-append">
                      <button type="button" className="btn msg-send-btn">
                        <i className="fab fa-telegram-plane" />
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {/* /Chat Right */}
            {/* Invite People */}
            <div className="chat-cont-right invite-sidebar-right">
              <div className="chat-header">
                <div className="heading-text">Invite Someone</div>
                <a href="#" className="close-btn" id="InviteClose">
                  <i className="feather-x" />
                </a>
              </div>
              <div className="message-body">
                <div className="chat-body">
                  <div className="chat-scroll">
                    <ul className="add-list">
                      <li className="add-listitem user-active">
                        <div className="person-info">
                          <img
                            src={Videocall}
                            alt="User Image"
                            className="avatar-img"
                          />
                          <div className="person-name">Shira</div>
                        </div>
                        <div className="list-body">
                          <ul className="action-info">
                            <li>
                              <a href="#" className="mute-vid">
                                <i className="feather-video" />
                              </a>
                            </li>
                            <li>
                              <a href="#" className="mute-mic">
                                <i className="feather-mic" />
                              </a>
                            </li>
                          </ul>
                        </div>
                      </li>
                      <li className="add-listitem">
                        <div className="person-info">
                          <img
                            src={user02}
                            alt="User Image"
                            className="avatar-img"
                          />
                          <div className="person-name">Linnea</div>
                        </div>
                        <div className="list-body">
                          <ul className="action-info">
                            <li>
                              <a href="#" className="mute-vid">
                                <i className="feather-video" />
                              </a>
                            </li>
                            <li>
                              <a href="#" className="mute-mic">
                                <i className="feather-mic" />
                              </a>
                            </li>
                          </ul>
                        </div>
                      </li>
                      <li className="add-listitem">
                        <div className="person-info">
                          <img
                            src={user01}
                            alt="User Image"
                            className="avatar-img"
                          />
                          <div className="person-name">Saba G</div>
                        </div>
                        <div className="list-body">
                          <ul className="action-info">
                            <li>
                              <a href="#" className="mute-vid">
                                <i className="feather-video" />
                              </a>
                            </li>
                            <li>
                              <a href="#" className="mute-mic">
                                <i className="feather-mic" />
                              </a>
                            </li>
                          </ul>
                        </div>
                      </li>
                      <li className="add-listitem">
                        <div className="person-info">
                          <div className="person-view">A</div>
                          <div className="person-name">Akshay</div>
                        </div>
                        <div className="list-body">
                          <ul className="action-info">
                            <li>
                              <a href="#" className="mute-vid text-primary">
                                <i className="feather-video-off" />
                              </a>
                            </li>
                            <li>
                              <a href="#" className="mute-mic">
                                <i className="feather-mic" />
                              </a>
                            </li>
                          </ul>
                        </div>
                      </li>
                    </ul>
                  </div>
                </div>
                <div className="chat-footer d-grid">
                  <button type="button" className="btn heading-text">
                    Invite Someone
                  </button>
                </div>
              </div>
            </div>
            {/* /Invite People */}
          </div>
          {/* /Main Wrapper */}
        </>
        )
}
export default Meetingcall2;
