// vuejs-template/template2/src/views/ForgotpasswordMobile.vue
<template>
	<div class="account-page ml-minus">
		<!-- Main Wrapper -->
        <div class="main-wrapper">          
            <!-- Page Content -->
            <div class="content align-items-center">
                    
            <div class="w-100 ">
                    <div class="login-left">
                        
                        <!-- Login Tab Content -->
                        <div class="account-content">
                            <div class="login-header">
                                <router-link to="/index">
                                    <img src="../assets/img/logo-full.png" alt="">
                                </router-link>
                            </div>
                            <div class="form-col">
                                <div class="login-text-details">
                                    <h3>Forgot Password</h3>
                                    <p>Confirm your Phone number and enter the OTP to send to your Registered Mobile Number</p>
                                </div>
                                <form>
                                    <div class="form-group">
                                        <label>Phone Number</label>
                                        <input class="form-control form-control-lg group_formcontrol" name="mobile" type="text">
                                    </div>
                                    <div class="form-group">
                                        <label class="custom-check d-flex flex-wrap ps-0 mt-3">
                                            Didnt recieve OTP ?  <a href="javascript:void(0);" class="ms-1" data-bs-toggle="modal" data-bs-target="#otp-success"> Resend OTP.</a>
                                        </label>
                                    </div>
                                    <div class="pt-3">
                                        <div class="text-center">
                                        <router-link to="/login-phone">
                                            <button class="btn newgroup_create btn-block d-block w-100" type="submit">Reset Password</button>
                                        </router-link>
                                        </div>
                                    </div>
                                </form>
                            </div>
                            <div class="back-btn-col text-center">
                                <router-link to="/index"><span><i class="fas fa-caret-left"></i></span> Back</router-link>
                            </div>
                        </div>
                        <!-- /Login Tab Content -->
                    </div>
                    <div class="login-right pwd-bg">
                    </div>
                </div>

            </div>      
            <!-- /Page Content -->
            
            <!-- OTP Success -->
                <div class="modal fade" id="otp-success">
                    <div class="modal-dialog modal-dialog-centered">
                        <div class="modal-content">
                            <div class="modal-body">
                                <div class="success-icon text-center">
                                    <i class="fas fa-check mb-3"></i>
                                    <p>OTP Sent to the Registered Mobile Number</p>
                                </div>    
                                <div class="modal-close text-end">
                                    <div class="close-modal" data-bs-dismiss="modal">
                                        <span>close</span>
                                    </div>
                                </div>
                            </div>       
                        </div>
                    </div>
                </div>
            <!-- /OTP Success -->
            
        </div>
        <!-- /Main Wrapper -->
    </div>
</template>
<script>
    export default {
        mounted() {
//Otp Verfication
    $('.digit-group').find('input').each(function() {
    $(this).attr('maxlength', 1);
        $(this).on('keyup', function(e) {
            var parent = $($(this).parent());

            if(e.keyCode === 8 || e.keyCode === 37) {
                var prev = parent.find('input#' + $(this).data('previous'));
                
                if(prev.length) {
                    $(prev).select();
                }
            } else if((e.keyCode >= 48 && e.keyCode <= 57) || (e.keyCode >= 65 && e.keyCode <= 90) || (e.keyCode >= 96 && e.keyCode <= 105) || e.keyCode === 39) {
                var next = parent.find('input#' + $(this).data('next'));
                
                if(next.length) {
                    $(next).select();
                } else {
                    if(parent.data('autosubmit')) {
                        parent.submit();
                    }
                }
            }
        });
    });

    $('.digit-group input').on('keyup', function(){
        var self = $(this);
        if ( self.val() != '' ) {
            self.addClass('active');
        } else {
            self.removeClass('active');
        }
    });
    
    }
}
    </script>

// reactjs-template/template2-rtl/src/frontend/pages/forgotpassword-mobile.jsx
import React,{ Component } from 'react';
import { BrowserRouter as Router, Route, Switch,HashRouter } from 'react-router-dom';
import { Button, Modal, Dropdown, DropdownItem, Tabs } from "react-bootstrap";

import LogoFull from '../assets/img/logo-full.png';

class Forgotpasswordmobile extends Component {
	componentDidMount() {
		$('body').addClass('account-page');
	}
	constructor(props, context) {
        super(props, context);
        this.handleShow = this.handleShow.bind(this);
        this.handleClose = this.handleClose.bind(this);
        this.state = {
          show: null
        };
    }
    handleClose() {
        this.setState({show: id});
    }
    handleShow(id) {
        this.setState({show: id});
    }
	render() {
  		return (
  			<div className="main-wrapper">
	            <div className="content align-items-center">
	            	<div className="w-100 ">
						<div className="login-left">
							
							<div className="account-content">
								<div className="login-header">
									<a href="/template2-rtl/">
	                                    <img src={LogoFull} alt="" />
	                                </a>
								</div>
								<div className="form-col">
									<div className="login-text-details">
										<h3>Forgot Password</h3>
										<p>Confirm your Phone number and enter the OTP to send to your Registered Mobile Number</p>
									</div>
									<form action="/template2-rtl/login-email">
										<div className="form-group">
											<label>Phone Number</label>
											<input className="form-control form-control-lg group_formcontrol" name="mobile" type="text" />
										</div>
										<div className="form-group">
											<label className="custom-check d-flex flex-wrap pl-0 mt-3">
												Didnt recieve OTP ?  <a href="#" className="ml-1" onClick={() => this.handleShow('Otpsuccess')}> Resend OTP.</a>
											</label>
										</div>
										<div className="pt-3">
											<div className="text-center">
												<button className="btn newgroup_create btn-block d-block w-100" type="submit">Reset Password</button>
											</div>
										</div>
									</form>
								</div>
								<div className="back-btn-col text-center">
								<a href="/template2-rtl/forgotpassword-email"><span><i className="fas fa-caret-left"></i></span> Back</a>
							</div>
							</div>
						</div>
						<div className="login-right  otp-bg">
						</div>
					</div>
	            </div>

	            <Modal show={this.state.show == 'Otpsuccess'} onHide={this.handleClose} animation={true} size="md" centered className="shadow-lg">
                    <Modal.Body>
                        <div className="success-icon text-center">
							<i className="fas fa-check mb-3"></i>
							<p>OTP Sent to the Registered Email id</p>
						</div> 
						<div className="modal-close text-right">
							<div className="close-modal" onClick={() => this.setState({ show: false })}>
								<span>close</span>
							</div>
						</div>
                    </Modal.Body>
                </Modal>

            </div>
  		)
  	}
 }

 export {Forgotpasswordmobile};
