// vuejs-template/template2/src/views/LoginEmail.vue
<template>
	<div class="account-page ml-minus">
		<!-- Main Wrapper -->
        <div class="main-wrapper">          
            <!-- Page Content -->
            <div class="content align-items-center">
                    
            <div class="w-100 ">
                    <div class="login-left">
                        
                        <!-- Login Tab Content -->
                        <div class="account-content">
                            <div class="login-header">
                                <router-link to="/index">
                                    <img src="../assets/img/logo-full.png" alt="">
                                </router-link>
                            </div>
                            <div class="form-col">
                                <div class="login-text-details">
                                    <h3>Log in</h3>
                                    <p>Login with your Data that you entered during your Registration</p>
                                </div>
                                <form>
                                    <div class="form-group">
                                        <label>Your Email</label>
                                        <input class="form-control form-control-lg group_formcontrol" name="email" type="email">
                                    </div>
                                    <div class="form-group">
                                        <label>Password</label>
                                        <input class="form-control form-control-lg group_formcontrol" name="password" type="text">
                                    </div>
                                    <div class="form-group">
                                        <label class="custom-check d-flex">
                                            <input type="checkbox">Keep me logged in
                                            <span class="checkmark"></span>
            
                                        </label>
                                    </div>
                                    <div class="pt-1">
                                        <div class="text-center">
                                        <router-link to="/index">
                                            <button class="btn newgroup_create btn-block d-block w-100" type="submit">Login</button>
                                        </router-link>
                                        </div>
                                    </div>
                                
                                <div class="text-center dont-have">Don’t have an account? <router-link to="/signup-email">Signup</router-link></div>
                                <div class="text-center mt-3">
                                    <span class="forgot-link">
                                        <router-link to="/forgotpassword-email" class="text-end">Forgot Password ?</router-link>
                                    </span>
                                </div>
                                </form>
                            </div>
                            <div class="back-btn-col text-center">
                                <router-link to="/index"><span><i class="fas fa-caret-left"></i></span> Back</router-link>
                            </div>
                        </div>
                        <!-- /Login Tab Content -->
                    </div>
                    <div class="login-right">
                    </div>
                </div>

            </div>      
            <!-- /Page Content -->
        </div>
        <!-- /Main Wrapper -->
    </div>
</template>

// reactjs-template/template2-rtl/src/frontend/pages/login-email.jsx
import React,{ Component } from 'react';
import { BrowserRouter as Router, Route, Switch,HashRouter } from 'react-router-dom';

import LogoFull from '../assets/img/logo-full.png';

class Loginemail extends Component {
	componentDidMount() {
		$('body').addClass('account-page');
	}
	render() {
  		return (
  			<div className="main-wrapper">
	            <div className="content align-items-center">
	            	<div className="w-100 ">
						<div className="login-left">
							
							<div className="account-content">
								<div className="login-header">
									<a href="/template2-rtl/">
	                                    <img src={LogoFull} alt="" />
	                                </a>
								</div>
								<div className="form-col">
									<div className="login-text-details">
										<h3>Log in</h3>
										<p>Login with your Data that you entered during your Registration</p>
									</div>
									<form action="/template2-rtl/">
		                                <div className="form-group">
		                                    <label>Your Email</label>
		                                    <input className="form-control form-control-lg group_formcontrol" name="email" type="email" />
		                                </div>
		                                <div className="form-group">
		                                    <label>Password</label>
		                                    <input className="form-control form-control-lg group_formcontrol" name="password" type="text" />
		                                </div>
		                                <div className="form-group">
		                                	<label className="custom-check d-flex">
		                                        <input type="checkbox" />Keep me logged in
		                                        <span className="checkmark"></span>
		        
		                                    </label>
		                                </div>
		                                <div className="pt-1">
		                                	<div className="text-center">
		                                     	<button className="btn newgroup_create btn-block d-block w-100" type="submit">Login</button>
		                                    </div>
		                                </div>
									
									<div className="text-center dont-have">Don’t have an account? <a href="/template2-rtl/signup-email">Signup</a></div>
									<div className="text-center mt-3">
										<span className="forgot-link">
											<a href="/template2-rtl/forgotpassword-email" className="text-right">Forgot Password ?</a>
										</span>
									</div>
									</form>
								</div>
								<div className="back-btn-col text-center">
									<a href="/template2-rtl/"><span><i className="fas fa-caret-left"></i></span> Back</a>
								</div>
							</div>
						</div>
						<div className="login-right">
						</div>
					</div>
	            </div>
            </div>
  		)
  	}
 }

 export {Loginemail};
