// reactjs-template/template2/src/admin/components/forgotpassword/index.jsx
import React, { Component } from 'react';

class Forgotpassword extends Component{
    render(){
        return(
            <div className="main-wrapper login-body">
                <div className="login-wrapper">
                    <div className="container">
                        <div className="loginbox">
                            <div className="login-right">
                                <div className="login-right-wrap">
                                    <h1>Forgot Password?</h1>
                                    <p className="account-subtitle">Enter your email to get a password reset link</p>
                                    <form action="/template2/admin/login">
                                        <div className="form-group">
                                            <input className="form-control" type="text" placeholder="Email" />
                                        </div>
                                        <div className="form-group mb-0">
                                            <button className="btn btn-primary btn-block" type="submit">Reset Password</button>
                                        </div>
                                    </form>
                                    <div className="text-center dont-have">Remember your password? <a href="/template2/admin/login">Login</a></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>    
        )
     }
  }
  
 export default Forgotpassword;

// vuejs-template/template-rtl/src/views/admin/ForgotPassword.vue
<template>
		<!-- Main Wrapper -->
        <div class="main-wrapper login-body">
            <div class="login-wrapper">
            	<div class="container">
                	<div class="loginbox">
                        <div class="login-right">
							<div class="login-right-wrap">
								<h1>Forgot Password?</h1>
								<p class="account-subtitle">Enter your email to get a password reset link</p>
								
								<!-- Form -->
								<form>
									<div class="form-group">
										<input class="form-control" type="text" placeholder="Email">
									</div>
									<div class="form-group mb-0">
									<router-link to="/admin/login">
										<button class="btn btn-primary btn-block" type="submit">Reset Password</button>
									</router-link>
									</div>
								</form>
								<!-- /Form -->
								<div class="text-center dont-have">Remember your password?<router-link to="/admin/login"> Login</router-link></div>
							</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
		<!-- /Main Wrapper -->
		
</template>
